components/LinksConatiners/LinkContainer.jsx, components/LinksConatiners/LinksContainer.tsx, components/LinksConatiners/index.ts, database/data.ts, pages/index.tsx
created link card on right pannel
=> chore: working on main container

components/LinksConatiners/LinkContainer.jsx
I have fixed the issue that I have opened few minutes ago #14
=> buttons changed to a tags and links fixed

pages/_document.tsx
adding google tag manager to site
=> chore: adding GTM

database/data.ts
=> Change undraw url

pages/animations/index.tsx, pages/colors/index.tsx, pages/design-inspiration/index.tsx, pages/fonts/index.tsx, pages/icons/index.tsx, pages/illustrations/index.tsx, pages/images/index.tsx, pages/testing/index.tsx, pages/themes-templates/index.tsx
=> fix: adding top margin

components/cards/index.tsx, database/data.ts, pages/animations/index.tsx, pages/colors/index.tsx, pages/design-inspiration/index.tsx, pages/fonts/index.tsx, pages/icons/index.tsx, pages/illustrations/index.tsx, pages/images/index.tsx, pages/testing/index.tsx, pages/themes-templates/index.tsx
=> Dev > main

components/SideNavbar/SideNavbarElement.tsx, package-lock.json
Closes #27 
This PR updates the code base to implement hover effects on the nav items.
Please do a review, your comments would be super helpful
=> Feature: Add hover effect to  Nav items [FIX for issue #27]

database/data.ts
=> add coolor link

database/data.ts
Added images link of kaboompics. It allows users to search pictures by color provides a complementary palette of colors in the photo.
=> chore:added new links

README.md
Fixes and Closes Issue #63 
Fixed spelling errors on line number 2 and 39
Have a great weekend :D
=> [Other] Closes Issue #63

components/LinksConatiners/LinkContainer.jsx, components/SideNavbar/SideNavbar.tsx, components/SideNavbar/SideNavbarElement.tsx, components/ThemeToggler/intex.ts, components/ThemeToggler/themeToggler.tsx, components/TopBar/TopBar.tsx, components/TopBar/index.ts, layouts/GeneralLayout.tsx, package.json, pages/_app.tsx, pages/animations/index.tsx, pages/colors/index.tsx, pages/design-inspiration/index.tsx, pages/fonts/index.tsx, pages/icons/index.tsx, pages/illustrations/index.tsx, pages/images/index.tsx, pages/testing/index.tsx, pages/themes-templates/index.tsx, tailwind.config.js
PR Fixes the Issue : #4 
changes:
- Darkmode config for Tailwind
- Dark mode Toggle button
- Topbar component to add Darkmode Toggler
- Add dark mode contrast color in relevant components
=> Feature: Dark mode support

database/data.ts
=> [Add] link to lottie files

database/data.ts
Added Link to type-scale.com under Frontend category, fonts subcategory
Question: Is this enough info in PR? I've used the in-browser editor to add this resource but would like to be sure it's a correct way because I would like to share many more good things I have bookmarked and don't want to make it troublesome for maintainers :)
=> [Add] type-scale.com

database/data.ts
=> [Add] Dribbble

README.md
=> Fixes and Closes Issue #97

components/ThemeToggler/themeToggler.tsx, components/TopBar/TopBar.tsx
=> hover effect of gihub and theme

pages/[subcategory].tsx
=> Update site title when clicked on Side navbar elements

README.md
=> Added a Logo and Tagline

README.md
Updated the Readme
Fixed the contributing guideline
=> Contributing Guideline link fixed in Readme

README.md
* The language has been refined and made more concise
* It provides a clearer and more welcoming description of the project's purpose.
Updated the readme. Thought it would be more engaging. Plus there were grammar mistakes in the previous one , if you want to update, I could do that as well!
=> updated readme with better choice of words

components/SideNavbar/SideNavbar.tsx, components/SideNavbar/SideNavbarElement.tsx, styles/globals.css
1. Colors improved for light mode
2. Scrollbar color is now changing according to themes (sidenavbar scrollbar)
=> chore: ui improvements

database/data.ts
=> chore: added new link (UI Color Picker)

.gitpod.yml, README.md
- Setup the Gitpod ready-to-code system.
- With [Gitpod.io](https://www.gitpod.io), you can easily build the website and install the necessary dependencies in one single click.
None yet.
[![Gitpod Ready-to-Code](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/rupali-codes/LinksHub/pull/156)
=> feat: Setup the Gitpod ready-to-code system

components/LinksContainer/LinkContainer.jsx, components/SideNavbar/SideNavbar.tsx, database/data.ts, types/index.ts
=> merge new-links into main

database/data.ts
- Add [Devicon](htttps://devicon.dev) to the icons list.
None.
=> chore: add Devicon to the icons list

components/SideNavbar/SideNavbarElement.tsx
Closes #162
Moved the border-bottom from the parent div to the inner NavLink text
Before:
After:
=> fixed rounded bottom border on navlinks

database/data.ts, types/index.ts
Add new category  named Resources and a subcategory named Blogs.
=> Add new category Resources & subcategory Blogs

components/LinksContainer/LinkContainer.jsx
Closes #150
Added an external link icon to the 'visit site' link which is shown on hover
=> added external link icon to visit site link

README.md, components/TopBar/TopBar.tsx
Added discord icon to the TopBar.
=> chore: add discord link in README & website (#201)

components/SideNavbar/SideNavBarCategory.tsx, components/SideNavbar/SideNavbar.tsx, components/SideNavbar/SideNavbarCategory.tsx, components/SideNavbar/SideNavbarCategoryList.tsx, components/SideNavbar/SideNavbarElement.tsx
Hi! I made categories collapsible in the `SideNavbar` component.
Closes #206
- Added `SideNavbarCategoryList` component with openByDefault property.
- Added `SideNavbarCategory` component with collapsible functionality.
- Added `hover` and `focus-visible` for the title of the category.
- I changed the order of CSS classes. (`SideNavbarCategoryList` , `SideNavbarCategory` and `SideNavbarElement`)
=> feat: Made the categories collapsible

package.json, pages/index.tsx
Added Typewriter effect in home page that shows all of our sub categories and guides to navigate through menu.
=> TypeWriterEffect in Home Page

components/Footer/Footer.tsx
=> fixing of the footer

styles/globals.css
Closes #208 
Default font-family changed
None
=> fix : Default font-family

.gitignore, CONTRIBUTING.md, components/cards/index.tsx, database/backend/validation.json, database/data.ts, database/frontend/animations.json, database/frontend/colors.json, database/frontend/design-inspirations.json, database/frontend/fonts.json, database/frontend/icons.json, database/frontend/illustrations.json, database/frontend/images.json, database/frontend/online-code-editors.json, database/frontend/ui-generators.json, database/resources/blogs.json, database/resources/hosting.json, database/youtube/android.json, database/youtube/data-structures.json, database/youtube/machine-learning.json, database/youtube/web-development.json, package-lock.json, package.json
This PR contains an auto generated unique ID for each resources
=> [clean-up] chores: code clean up and bug fixes

README.md
#213 
addition of the code lines in the readme.md file -
To run and view the application on localhost
```sh
npm run dev
```
=> [Feat] Addition of the run command in README.md file

database/data.ts, database/index.ts, database/youtube/web3-metaverse, database/youtube/web3-metaverse.json, types/index.ts
=> Adding a sub-category under youtube

database/frontend/illustrations.json
=> added illustration resources

database/frontend/icons.json
Added two websites 
@rupali-codes you made an awesome website.
=> Update: Added two icons websites

database/frontend/design-inspirations.json
Just added another website called dopeui.
=> Update: Added dope ui link

components/ThemeToggler/themeToggler.tsx
Closes #235 
Check file _components/ThemeToggler/themeToggler.tsx_
NA
=> [Fix][OTHER] change theme toggler color

components/TopBar/TopBar.tsx
Closes #161 
made the topbar sticky on both theme
=> fix: vertical overflow issue in the home page

database/frontend/online-code-editors.json
Added Replit in Onine Code editors
=> Added Replit

CONTRIBUTING.md
I made grammatical improvements to the Contributing file. For instance, the note in the Details section was missing a comma after its introductory phrases(the word note was missing a colon. See picture one for reference)
This is my first time contributing to this project, so any feedback is helpful.
=> Made grammatical changes

database/frontend/themes-templates.json
Added 3 sites in Themes-Templates
[html.design](https://html.design/)
[html5 up](https://html5up.net/)
[template mo](https://templatemo.com/)
=> Added in themes-templates

components/popup/index.tsx
Closes #274 [BUG] Modal Responsiveness
1. changed in the components/popup/index.tsx file.
=> Solved the popup responsive modal issue

database/frontend/illustrations.json
New resource added named " StorySet ", which contains illustrations that are free and customizable.
=> Added a new resource for illustrations named StorySet

components/SideNavbar/SideNavbarCategory.tsx, components/SideNavbar/SideNavbarElement.tsx
=> Feat restyle sidebar

database/frontend/colors.json
color hunt is useful in finding color palettes
=> chore: add Color Hunt in Colors Panel

components/Aside/Aside.tsx, components/Backdrop/Backdrop.tsx, components/Footer/Footer.tsx, components/Header/Header.tsx, components/LinksContainer/LinkContainer.jsx, components/SideNavbar/SideNavbar.tsx, components/SideNavbar/SideNavbarBody.tsx, components/SideNavbar/SideNavbarHeader.tsx, components/SocialMedia/SocialMediaIconsList.tsx, components/TopBar/TopBar.tsx, components/cards/index.tsx, components/popup/index.tsx, hooks/useDelayUnmount.ts, layouts/GeneralLayout.tsx, pages/[subcategory]/index.tsx, pages/_document.tsx, pages/index.tsx, styles/globals.css, tailwind.config.js
Hi! I improved the site structure
Closes #302
Improved the site layout with grid.
Added `overlay-root` to the `_document.tsx`.
- Stores the active `popup` and `SideNavbar` component.
Improved SideNavbar
- Has the social icons in mobile view.
- Improved the design of the `SideNavbar` in mobile view and added an `aside` component from `lg`.
Added a fix header
- Stores the logo, the `category name`, the social icons, the theme toggle and the menu button.
- The `category` name is under the `header` in mobile view.
Improved the `popup` component
- Use the reusable Backdrop.
=> feat: Improved the site structure

database/frontend/online-code-editors.json
=> Added Codesandbox

README.md
Closes [#298](https://github.com/rupali-codes/LinksHub/issues/298)
I removed the second Discord but then I thought it would be best to remove the entire Community section since the “Welcome to LinksHub” section describes the kind of community contributors will partake in. See screenshot below for context.
Feedback will be greatly appreciated
=> Removed second Discord link

database/frontend/animations.json, database/frontend/design-inspirations.json, database/resources/blogs.json
Closes : #310 
Closes : #312
Closes : #273 
Closes : #272 
Closes : #270
=> added new resources

database/backend/testing.json, database/data.ts, database/index.ts, database/youtube/testing.json
=> testing.json file filled with data

database/Other/Github.json
Added resource for Other Category in Github.json
=> Update in Other Category

database/frontend/animations.json
=> Animate On Scroll

.github/ISSUE_TEMPLATE/add_link.yml, .gitignore, database/backend/architecture.json, database/data.ts, database/frontend/themes-templates.json, database/index.ts, database/youtube/web-development.json
Closes #289
Closes #288 
Closes #287
- New backend subcategory architecture
=> Links and Issue Template fix

.github/dependabot.yml, .github/workflows/greetings.yml, .github/workflows/jsoncheck.yml
solved #365 
- greetings.yml
- jsoncheck.yml
- dependabot.yml
=> ci: added GitHub Actions

components/CopyToClipboard/CopyToClipboard.tsx, components/CopyToClipboard/index.ts, components/LinksContainer/LinkContainer.jsx, components/popup/index.tsx, hooks/useCopyToClipboard.ts, package-lock.json, package.json
Closes #362 
Added CopyToClipboard component and hook
=> feat: Add copy link to clipboard button(rupali-codes#362)

database/youtube/web-development.json
Added  Code with Ania Kubów YT channel in the youtube section in web development topic.
=> <added new Link> Code with Ania Kubów YT channel

database/data.ts, package-lock.json, package.json
[BUG] Package Deprecated #380 
Solved #380 
react-uuid is deprecated so i used uuid
https://www.npmjs.com/package/uuid
=> changed from react-uuid to uuid

database/frontend/design-inspirations.json
- Added new resource in category ``Design Inspiration`` in Frontend.
=> added new resource

database/frontend/online-code-editors.json
Closes #385 
Added StackBlitz in online code editor category
=> add: stackblitz in online code editor category

database/frontend/design-inspirations.json
Remove duplicate link
Maybe we should add a check for duplicate links? Wdyt 🤔
=> fix: removed duplicate Screeenlane link

database/youtube/data-structures.json
Closes #398 added the Abdul Bari's channel in youtube category under ds subcategory
=> 'Closes #398' added the abdul bari DSA channel

database/youtube/web-development.json
Adds JavaScript Mastery 
Closes #403 to add JavaScript Mastery in youtube category.
=> Closes #403 Added JavaScript Mastery

.github/workflows/greetings.yml
closes #413
- Replacing the echo command with a custom action that displays a more personalized message.
- Adding the issue-message argument
=> ci: fix greeting action

README.md
=> chore: update socials text

.github/workflows/greetings.yml, README.md
=> fix: GitHub actions & update socials text in readme

database/data.ts, database/youtube/web3-metaverse.json
Closes #438 
- Capitalised CSS
- Capitalised 'f' in FreeCodeCamp
-  Location: LinksHub/database/data.ts
- Location: LinksHub/database/youtube/web3-metaverse.json
=> Capitalised CSS (subcategory) & FreeCodeCamp(YouTube>Web3)

README.md
The banner image on the Readme file is updated with this image file - https://user-images.githubusercontent.com/78981177/232279811-a219b1b5-6383-4ace-9614-24c6b258fec0.png
This PR Closes #446
=> Updated the Banner Image on the Readme file

pages/index.tsx
Closes[#331](https://github.com/rupali-codes/LinksHub/issues/331)
I added the website's description to the hero section. 
I never worked with Typescript before so constructive feedback would be helpful.
=> added description of LinksHub

database/youtube/web3-metaverse.json
Added Sarah's YouTube channel to web3-metaverse.json file
N/A
=> Added: Sarah Benson

database/youtube/web-development.json
Closes #456 
Added link to Hussein Nasser's Youtube channel
=> chore: Added Hussein Nasser (#456)

database/data.ts, database/frontend/react.json, database/index.ts, database/resources/e-book.json, database/youtube/machine-learning.json, types/index.ts
1 - Added a section for Tensorflow for Deeplearning under youtube
=> Added resources for (Tensorflow for deep learning)

database/youtube/css.json
Adds new Youtube channel for CSS resources
=> feat: Animation Coding

database/youtube/web3-metaverse.json, pages/index.tsx
=> merge dev into main

database/resources/blogs.json
=> added hacker news site link

database/data.ts, database/index.ts, database/youtube/computer-science.json
Closes #479 
Added Gate Smashers in Youtube section (sub-category Computer Science)
=> add gate smashers #479

components/Footer/Footer.tsx
closes #489 
Text **open-source community** was not referring to any link. added mentioned link to it
before
after
=> issue [CHORE] add LinksHub contributors link in footer of the site #489

database/languages/python.json
=> Fixes issue#493

.github/ISSUE_TEMPLATE/add_link.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml
I have updated template code and added option for if the person is willing to work on the issue or not
=> chore: update templates

database/opensource/opensource_blogs.json
Fixes #529 
Added my blog series to the open source category 
Feedback would be appreciated
=> feat: add my blog series

database/frontend/icons.json
Closes #526 
I added Tabler Icons to icons file under frontend category
=> Added tabler icons link

pages/_document.tsx
##Fixes issue
Closes #504 
Added the open graph meta tags in the _document.tsx to improve the way our website looks when shared.
The changes can be observed after pasting the deployed link on:
1. [LinkedIn post inspector](https://www.linkedin.com/post-inspector/inspect/)
2. [Twitter post validator](https://tweetpik.com/twitter-card-validator)
=> perf: add opengraph meta tags to enhance SEO

database/frontend/icons.json
Closes #528
Heroicons  link is added to frontend category
=> [Add] Heroicons

components/BackToTop/BackToTopButton.tsx, components/Cards/Card.tsx, components/CopyToClipboard/CopyToClipboard.tsx, components/Footer/Footer.tsx, components/NewIssue/NewIssue.tsx, components/Searchbar/Searchbar.tsx, components/SideNavbar/SideNavbarCategory.tsx, components/SideNavbar/SideNavbarElement.tsx, components/ThemeToggler/themeToggler.tsx, components/logo/index.tsx, components/popup/index.tsx, pages/index.tsx
Fixes #442
Applies a set of accessibility touchups to address issues detected by:
1. Running the [aXe browser extension](https://www.deque.com/axe/browser-extensions) on the page
2. Use a screenreader (e.g. [macOS VoiceOver](https://support.apple.com/guide/voiceover/welcome/mac)) to navigate through the page
<table>
<thead>
<tr>
<th>Mode</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>Dark mode</th>
<td><img alt="Before dark mode screenshot showing not enough color contrast in some text" src="https://github.com/rupali-codes/LinksHub/assets/3335181/3639a055-2ae5-4fe0-a323-c0efc39b6a56" /></td>
<td><img alt="After dark mode screenshot showing enough color contrast in some text" src="https://github.com/rupali-codes/LinksHub/assets/3335181/6d0a1532-4e96-4fba-b13b-10ca916f3e …
=> fix: accessibility issues

database/frontend/icons.json, database/frontend/themes-templates.json
Closes #541
VistaCreate link is added to frontend category on Theme & Template file.
=> Chore: VistaCreate

database/languages/javascript.json
=> Added two Javascript resources

database/frontend/icons.json
Closes #580 
- Added new icons resource
hots
=> add: animted-fluent-emojis in db

database/languages/golang.json
closes #484 
- Added resources for Golang series
hey! thanks for reviewing my PR do let me know if there is any change required
=> feat: added a golang resource

database/youtube/web-development.json
Closes #576
Add new YouTube link in web development section "Developedbyed"
=> Add new YouTube link for web development 'developedbyed'

database/opensource/opensource_blogs.json
=> Added two opensource link

database/backend/authentication.json
=> Firebase-Authentication guide added to backend/authentication.json

components/SideNavbar/SideNavbarElement.tsx
=> fix : changed hover color

database/data.ts, database/index.ts, database/languages/golang.json, database/ml&ai/datascience.json, database/ml&ai/deeplearning.json, database/ml&ai/ml.json, database/resources/blogs.json, database/youtube/machine-learning.json, types/index.ts
…, dl and data science'
2. also added a section for DeepLearningAI in ```database/youtube/machine-learning.json```
3. fixed a bug in displaying the ```golang``` section in main branch
4. added a new blog card for ```blogs.json```
5. modified the ```types/index.ts```, ```data.ts``` and ```index.ts``` sections for displaying the changes
Issue : #614 
1. Created a new category **ML, AI & DATA**
2. Created subcategories for _Machine Learning_, _Deep Learning_ and _Data Science_
3. Created a new entry in the `blogs.json` file for _Andrew Ng's blog_ on AI, ML and Deep Learning
4. Created a new entry in `machine-learning.json` file for DeepLearningAI's youtube channel
5. Added a link in `database/languages/golang.json` file, which was empty [🙃](https://emojipedia.org/upside-down-face/)
Please …
=> #GSSoC2023 1.Added section 'ml,ai and data' and provided links for ML, Data Science and Deep Learning 

database/languages/python.json
Closes #612 
Add new resource in Python, Subcategory of "Languages".
=> Python programiz in Python Language

database/youtube/data-structures.json
Closes #583 
Added a new resources under YouTube subcategory.
This will also be a great addition to the resources and this PR would be my second contribution to the project.
=> [Add] Kunal Kushwaha's Java Data Structures and Algorithms Course with Interview Preparation

.github/ISSUE_TEMPLATE/add_link.yml
add open source option to add_links template
=> open source option added to issue template

.github/ISSUE_TEMPLATE/add_link.yml, .github/workflows/close_old_prs.yaml
I have created a new github actions for closing old prs with a time limit of 30 days(can be changed as per convenience)
=> Workflow for closing old prs added

components/SideNavbar/SideNavbarBody.tsx, components/SideNavbar/SideNavbarCategory.tsx, components/SideNavbar/SideNavbarCategoryList.tsx, components/SideNavbar/SideNavbarElement.tsx, hooks/useSidebarSearch.ts
Closes #669 
Following changes have been made for better UX
- Multiple sidebar sections are expandable.
- While searching, the sections expand to show the results properly lest the user gets confused.
- After search is closed, the sidebar sections revert back to their original state.
https://github.com/rupali-codes/LinksHub/assets/73349037/bf657b3a-f67c-491d-85c7-e2281f6a42f9
=> fix: search ux improvement

database/languages/python.json
Closes #606 
Added Python language tutorial in language section of database.
Please review my change and add it to your main branch
=> [Add] Interactive Python Tutorial Website 

database/youtube/data-structures.json
Closes  #608 
Added Algorithm tutorial in data structures section of Database.
##Screenshot
Please review my change and add it to your main branch
=> chore: added dsa resource

database/opensource/projects.json
=> Added 'Open Source Contributions' to 'OPENSOURCE'

database/frontend/colors.json
#602 - Added Ai color palette generator
ColorMagic is an AI color palette generator. Generate colors by entering the keyword into the textbox,
Frontend
=> AI color generator

database/opensource/projects.json
Closes #618
Added the Good Docs Project to the opensource projects section
Please let me know if any additional changes are needed.
=> chore: Added Good Docs Project in opensource projects category

database/frontend/ui-generators.json
=> New UI- Generator added

database/youtube/web-development.json
Closes #635   
I added a new link for Youtube in the sub-category of web development.
=> chore: added new youtube link in subcategory web-development

.github/workflows/close_old_prs.yaml, database/youtube/machine-learning.json
Closes  #631 
Added Machine Learning Course on Youtube by 5 Minutes Engineering in youtube section of database. 
Kindly review and merge my contribution to your main branch. Thank you for providing me this opportunity to work upon your project. GSSoC'23 open Source Contributor.
=> [Add] Machine Learning Course by 5 mins Engineering

database/resources/blogs.json
I  added  content in the blog section #630
=> updated blog section

database/languages/javascript.json
Closes #697 
Added [Full stack JavaScript by odin project](https://www.theodinproject.com/paths/full-stack-javascript)
=> chore: added Full stack JavaScript by odin project

.vscode/settings.json, database/data.ts, database/index.ts, database/youtube/competitive-programming.json, tsconfig.json
Closes #650 
- added a competitive programming section under Youtube
- added 3 channels under that category.
=> added competitive programming section under Youtube

database/data.ts, database/index.ts, database/languages/typescript.json
Closes #622
1. Added TypeScript as a prominent language in the language section.
2. Added a list of curated resources for learning TypeScript, including official documentation, and community-driven learning platforms.
3. Ensured that the resource links are up-to-date and accessible to provide the most relevant and reliable learning material for developers.
=> Added TypeScript to the Language Section

database/frontend/animations.json
`chore: Added new links of animation tools`
Closes #724 
<br>
=> Added 2 new animation tool

database/Other/devtools.json
Closes #682 
added website link of code crafters.
=> chore: added codecrafters

database/youtube/web-development.json
Close #667 
Add Youtube link of Thapa Technical provide hindi content on web-development.
=> Add Thapa Technical Youtube link

database/youtube/css.json, tsconfig.json
=> Chore: Added CSS Playlist Link 

database/backend/authentication.json
Closes #595 
Added [NextAuth.js](https://next-auth.js.org) in ***subcategory:*** **Authentication**, ***category:*** **Backend**
=> chore: added nextauth in authentication backend

database/frontend/colors.json
Closes #632
A new Resource in the frontend Section under the subcategory of Colors is added.
=> "Added New Frontend Resource"

database/opensource/tools.json, database/other/github.json
I've added some github and open source tools which will help those who are beginners in open source
#770
=> added some tools

database/youtube/web-development.json
- Added new youtube channel named `Slaying the dragon` under web development
- The `Slaying the dragon` is one if the best youtube resource on web development so i added this to the `json` file
=> add: slaying the dragon youtube channel for web-development

database/frontend/illustrations.json
Closes #664 
- added new resource in illustrations
=> chore: added new resource in illustrations

database/frontend/react.json
Closes (#706)
- [Add] React Official Documentation and Mosh's React tutorial
=> Added new resources in React Js ( Frontend )

CONTRIBUTING.md, database/resources/blogs.json
- Added a Blog JavaScript top 10 tips and tricks, in the blogs.json
(Named as JavaScript Tricks-Raj's Blog).
- Issue No #756 
#gssoc 23
=> chore: add new JavaScript resources

database/other/devtools.json
=> chore: add Deepsource under Other in devtools

database/frontend/illustrations.json
=> chore: Add GetIllustrations in frontend category

database/youtube/machine-learning.json
Closes #762  
Added a YouTube channel named "Two Minute Papers". This channel covers a detailed explanation of many Artificial Intelligence and Machine Learning Research Papers. The explanation is neat, well-detailed, interesting and you would be watching the whole video without getting bored! The channel provides the visuals of the Model/Application in work while explanation. At last, I would always recommend this channel to anyone interested in AI and ML.
=> chore: Add "Two Minute Papers" in ML in YouTube

.github/FUNDING.yml
Added sponsor button in the repo
=> chore: add sponsor button in the repo

database/youtube/web-development.json
Added 2 resources in the youtube section under web-development. 
This closes #783 and #782
=> Added the links in the youtube section sucessfully

database/youtube/competitive-programming.json, database/youtube/computer-science.json
Added 3 resources in 2 different categories
1. Computer Science: 
> 5 Minutes Engineering
> Jenny's Lectures CS IT
2. Competitive Programming:
> Luv
=> Added 3 resources in 2 different categories

database/opensource/projects.json
=> Added new open source project

database/languages/javascript.json
Closes #777 
Added [Learn Js](https://learn-js.org/)
=> chore: Added Learn Js

database/index.ts, database/youtube/machine-learning.json, database/youtube/tensorflow.json
#775
I have incorporated an additional learning resource for TensorFlow and established a dedicated JSON file to facilitate the inclusion of future resources pertaining to TensorFlow.
=> chore: Daniel Bourke Youtube Channel

database/youtube/web-development.json
=> Full stack Web Development YT link added

database/resources/e-book.json
- Closes #800
- Added '*Eloquent JavaScript*' e-book for resources at `e-book.js` file
=> chore: add eloquent javascript e-book to resources

database/languages/golang.json
-->  Closes #780 
--> Added link to Go subcategory and Languages category.
=> Add Practical Go lessons

database/youtube/web-development.json
Added 1 resource in the youtube section under Web Development (PedroTechnologies).
This closes #784
=> added PedroTechnologies link

database/data.ts, database/frontend/accessibility.json, database/index.ts
Closes #794 
- Added `accessibility.json` to frontend folder
- Added resources to the `accessibility.json` 
- Added ` { name: 'accessibility', url: '/accessibility' }` to `database/data.ts`
- Added `export { default as accessibility } from './frontend/accessibility.json'` to `database/index.ts`
Hope everything checks out, thanks.
=> Chore: add Accessibility subcategory and resources to Frontend

database/data.ts, database/index.ts, database/youtube/fintech.json, types/index.ts
Closes : #727 
I added new subcategory for Fintech under Youtube section. In Fintech I have added new links for 5 youtube channels which i had mentioned earlier in my issue.
=> Added Fintech Section Under Youtube

database/opensource/projects.json
=> added new awesome opensource project

database/resources/project-ideas.json
PR fixes an open issue , 'Closes #812 '
It adds Artificial Intelligence projects in project-ideas of resources .
Kindly review this
Screenshot
=> Added Artificial Intelligence Projects related to issue-#812

components/SocialMedia/SocialMediaIconsList.tsx
=> [Update]: LinksHub Twitter handle

database/backend/database.json
Closes #836 
Added Firebase Database docs.
=> Add Firebase Database

database/frontend/ui-generators.json
Closes #841 
I have incorporated the CSS Grid Generator into the suite of UI Generators.
=> chore: Add CSS Grid Generator

database/other/devtools.json
Closes #844 
Added [SmallDevTools](https://smalldev.tools/)
=> chore: added SmallDevTools

database/youtube/data-structures.json
Added the resource under the youtube section
Closes the issue number #839
=> Added new resource DSA playlist

database/backend/database.json
closes #885 
- Add Tigris to the list of databases
=> Add Tigris as one of open source databases

database/data.ts, database/index.ts, database/languages/ruby.json
=> feat: add ruby subcategory under languages

database/opensource/tools.json
Closes #834
added geeksrepo in open source tools
=> added geekrepos in open source tools

components/Searchbar/Searchbar.tsx
I have improved search button style
=> chore: improve search button style

database/frontend/fonts.json
Closes #562
Added Fontesk to frontend database under subcategory fonts
Located under "fonts" in the "frontend" folder
=> chore: added Fontesk to frontend database under subcategory fonts

database/frontend/colors.json
=> chore: add AI Colors under the frontend/colors subcategory

database/resources/blogs.json
Added the blog
closes the issue number #868 
Added a new resource under blog section
=> Added new blog for react

database/resources/blogs.json
PR fixes an open issue , Closes #881 . 
I have added the blog in the Blogs subcategory within the resources category . 
Kindly review this .
Screenshot
=> Added the blog related to issue-881

database/other/devtools.json
Closes #863 
Added [Devhints](https://devhints.io/)
=> chore: added Devhints

components/SideNavbar/SideNavbarBody.tsx
Closes #252 
Now, There is no delay while switching themes
https://www.awesomescreenshot.com/video/17978839?key=f91cbb322e34e1a1d9aceb42b5e468e0
https://www.awesomescreenshot.com/video/17978898?key=3aa1d7afb63bf4dee3ae3c72c5f865ff
NaN
=> fix: delay in color change in scrollbar #252

database/frontend/icons.json
Closes #872 
I have integrated the Icon Finder website within the Icons category suite.
=> chore: Add Icon Finder

database/frontend/online-code-editors.json
Closes #907
The link and description of the OnlineGDB has been updated
|Before | After|
|----- |----- |
|![Screenshot 2023-06-03 050559](https://github.com/rupali-codes/LinksHub/assets/94990764/510a67b4-c892-4bf3-b019-439a9c5ec6c6) |![Screenshot 2023-06-03 072919](https://github.com/rupali-codes/LinksHub/assets/94990764/7d878795-84df-44c8-8e5c-c65ee1bb37e9) |
I have changed the description of the OnlineGDB alongwith the Link
=> FIX : OnlineGDB link

database/frontend/online-code-editors.json, styles/globals.css
Closes #905 
The website has native scrollbar as overall
The scrollbar can be customized to match the website theme and to improve UI.
_If in place of browser's default scrollbar, we use the custom scrollbar used in left panel, for the whole website, then the overall UI of website will be enhanced_
|Light mode |Dark mode |
|---- |---- |
|![Screenshot 2023-06-04 015847](https://github.com/rupali-codes/LinksHub/assets/94990764/6ae564a9-cd4f-4c1a-a6c7-d81fbfafe3f7) | ![Screenshot 2023-06-04 015832](https://github.com/rupali-codes/LinksHub/assets/94990764/8efbdcc3-a782-4b99-93c1-ac7e7b675853)
The Main scrollbar has been changed according to scrollbar present in left panel
=> ADD : Custom Scrollbar

database/frontend/ui-generators.json
Closes #908 
Name Changed  "universe"  to "uiverse"  in UI generator
=> Typo error for uiverse card

.github/workflows/greetings.yml
- #871 
- Some minor changes in typo of `greetings.yml` workflow script
- Changed typo for both `issue` & `pull request`
| | |
| :---: | :---: |
| **CURRENT** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/857efa4e-b10c-4733-8e07-a56998c4a5fa)| 
| **PROPOSED CHANGES** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/26849e50-5a8b-4ce3-a3b3-e06519618c12) | 
- The required necessary labels like `gssoc23` and `level` labels are not added for the merged PR: #870 (The issue is not closed to).
- I'm note this here because the `GSSoC`'s Backend can't count this PR without necessary labels.
- Please make sure to add those necessary labels, Thanks!
=> update: typo for greetings.yml workflow script

database/data.ts, database/index.ts, database/languages/c-programming.json, database/opensource/tools.json
=> feat: add C Programming subcategory in Languages

database/frontend/illustrations.json
=> chore: add Awesome Illustrations 4 Projects in frontend/illustrations

database/resources/blogs.json
Closes #896
I have integrated the Daily.dev website within the blogs category suite.
=> chore: Add daily.dev

database/resources/project-ideas.json
PR fixes an open issue , Closes #923 
It adds Cloud Computing projects in project-ideas of resources .
Kindly review this
Screenshot
=> Added Cloud Computing projects related to issue-923

database/data.ts, database/frontend/videos.json, database/index.ts
=> feat: add videos subcategory in frontend

database/frontend/ui-generators.json
[Add] <SuperDesigner.Co> Closes #883
=> [ADD] <SuperDesigner.Co>

database/languages/typescript.json
Closes [#919 ](https://github.com/rupali-codes/LinksHub/issues/919)
I have added  the new resource in typescript language section.
=> Added typescript resource for the issue 919

.github/ISSUE_TEMPLATE/documentation.yml
Closes #930 
I created a DOCS issue template 
Feedback would be greatly appreciated.
=> [fix] Create documentation.yml

database/other/other-resources.json
Closes #939 
Added [Developer Roadmaps](https://roadmap.sh/)
=> chore: add developer roadmaps to other/other-resources

.github/ISSUE_TEMPLATE/documentation.yml
Closes #958 
- Made the `issue description` field mandatory.
- Fixed the links.
- Removed the checklist for `category` and `subcategory` as it is irrelevant.
> Followed proper conventions
=> docs: update docs issue form with correct links

database/youtube/tensorflow.json
Added a new resource
closes #869 
Added new yt playlist for learning tensorflow
=> Added new youtube playlist

layouts/GeneralLayout.tsx
Closes #855 
- according to MDN semantic reference
- I'm not sure if this is all that needs to be done. I'm open to any changes.
=> chore: wrapped Aside component with nav

database/data.ts, database/index.ts, database/youtube/game-development.json
Closes #890
- I can remove the empty json resource
=> feat: add Game Development subcategory under YouTube

.github/ISSUE_TEMPLATE/documentation.yml, database/frontend/online-code-editors.json
Closes #906 
Added data for StackEdit under Frontend -> online-code-editors 
> StackEdit is a user-friendly online markdown editor with real-time collaboration and cloud storage integration, making writing > and editing documents effortless and accessible from anywhere.
The code added is : 
```
{
"name": "StackEdit",
"description": "StackEdit is a user-friendly online markdown editor with real-time collaboration and cloud storage integration, making writing and editing documents effortless and accessible from anywhere.",
"url": "https://stackedit.io/",
"category": "frontend",
"subcategory": "online-code-editors"
},
```
=> ADD : stackedit.io under online editors

database/frontend/react.json
=> Removed multiple resource of react 

components/SideNavbar/SideNavbarCategory.tsx
Closes #596 #747
I have added a smooth transition for the opening and closing of the accordion in the sidebar.
https://github.com/rupali-codes/LinksHub/assets/77151837/fe6aa947-9f6f-47a9-ba32-0750e55607ff
For the file where I did my changes, there is an "isOpen" prop that is no more needed. However, I did not remove it. And honestly speaking, this seemed a bit more than just a level 1 issue 😅
=> chore: added smooth transition for sidebar accordion

.github/CODEOWNERS
Closes #864 
I added @ujjawaltyagii to the CODEOWNERS file 
@ujjawaltyagii and @rupali-codes, a couple of errors came up, so helping me solve them would be greatly appreciated.
=> [fix] Revised CODEOWNERS file

database/frontend/ui-generators.json
Added new website (Glassmorphism CSS Generator) in Frontend UI-generator ssection
Closes : #985
=> Added Glassmorphism CSS Generator

styles/globals.css
This PR contains the modified code for the Homepage's paragraph alignment. This PR is the output of the following issue:
Homepage Paragraph Alignment #992
Closes #992
Homepage's paragraph has equally aligned.
Share your valuable review or any kind of improvement suggestion in PR.
=> Homepage Paragraph Alignment Correction

database/backend/security.json
closes #946 
added Django forbid in the backend
=> added Django Forbid

database/other/communities.json
Added GDG community link in communities section
close #964
=> chore: added GDG community link in communities section issue-964

database/frontend/colors.json
- Added `ColorClaim` resource to Frontend -> colors category.
=> chore: add colorclaim resource

database/frontend/illustrations.json
Closes : #937 
- Added an resource which contains 900+ High quality illustrations and animations in 27 different styles. 
(Frontend > Illustrations)
=> Add : Illustration resource

database/languages/c-programming.json
added Resources for C Language
https://github.com/rupali-codes/LinksHub/issues/1066
added Resources for C Language Learning Resources Links
=> added c-programming Resources. 

.github/ISSUE_TEMPLATE/refactor_code.yml
Resolves #1064 
- Make sure to add label `goal: refactor` in the repository
=> docs: add refactor issue form

components/SideNavbar/SideNavbarCategoryList.tsx
This PR closes issue: #1043 
- `components/SideNavbar/SideNavbarCategoryList.tsx`
[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/d1d7e648-8ef3-44b2-8a43-e9db3b5d77dd)
Please review this PR.
Thanks
=> Fix bug: display log messages on browser's console

database/frontend/colors.json
Closes #1027 
- Added `FarbVélo` resource to Frontend -> colors category.
=> chore: add color resource ✨

database/frontend/colors.json
I have added a color resource to the website.
=> Add a Color Resource

database/frontend/icons.json
Closes #1085 
I have added the free icon generator named Favicon. Please review it and If it is fine then please merge it to the main branch.🙏
=> chore: add favicon in frontend/icons

database/other/communities.json
Fixes #1010
Added 3 new Student Ambassador Programs under communities sub-section
=> added new programs under Community sub-category

README.md
This PR fixes   issue #1083
In the sentence "Before getting into it, it make you sure you have pnpm installed," was changed to "make sure" instead of "it make sure."
In the sentence "Push your changes into your branch," was changed to "Push your changes to your branch."
=> replaced spelling errors

components/Footer/Footer.tsx
Resolves #1074
> Dark mode
> Light mode
=> feat: add theme styled links in the footer

database/frontend/ui-generators.json
- Added [Tailwind Awesome](https://www.tailwindawesome.com/?technology=3) to Frontend -> UI Generators
This PR is a part of **GSSoC'23**
=> chore: added resource for tailwindCSS in UI generators

.github/ISSUE_TEMPLATE/category_description.yml, CONTRIBUTING.md, README.md
closes #1098 
1.Created a issue template
2. Updated CONTRIBUTING.md
3. updated README.md
=> Add support for adding subcategories description #1098

database/frontend/fonts.json
Closes #1108
I have added a font resource to the website.
=> Add Font Awesome

components/BackToTop/BackToTopButton.tsx
Closes #1138 
- I have addressed the concerns mentioned in the issue description. If you would like to know more, please let me know.
=> refactor: backToTopButton Component

components/Cards/Card.tsx
Closes #1136 
- I have addressed the concerns mentioned in the issue description. If you would like to know more, please let me know.
=> refactor: card component

components/Cards/CardsList.tsx
Closes #1137
- I have addressed the concerns mentioned in the issue description. If you would like to know more, please let me know.
=> refactor: cardList component

components/Header/Header.tsx, components/ThemeToggler/themeToggler.tsx
Closes #1139 
- I have addressed the concerns mentioned in the issue description. If you would like to know more, please let me know.
=> refactor: themeToggler and header component

database/youtube/android.json
##1104
Closes #1104 
Added youtube playlist link for android development
=> Added youtube playlist link for android development

database/frontend/animations.json
=> Added the  CSS Scan website to the LinksHub

database/frontend/colors.json
Closes #1168 
- Added `Eva Colors` a color resource which can be used to generate colors using deep learning by AI
- The resource mentioned on the issue `Instahues` is not working properly, I think the domain may be taken down for some sort of issues.
- Yesterday it was fine when i visited that, but i don't know what happened today.
- So i came with a new color resource `Eva Colors`
=> chore: add color resource for frontend ✨

database/frontend/ui-generators.json
CLOSES #1111 
Added a link which can generate CSS code for Patterns
=> chore : Added link for CSS Pattern Generator

database/frontend/images.json
Closes #1213 
Added the link and desc of the "Getty images" link in the images.json file
=> Added a new link in the images section of frontend

database/backend/authentication.json, database/backend/database.json
Closes #1219 
Added Appwrite as database and authentication inside the database folder.
=> Added Appwrite for authentication and database

database/youtube/machine-learning.json
=> adding 100 days machine learning playlist

database/youtube/android.json
Closes #1147 
Added youtube resource for android development
=> Added youtube resource for android development

database/resources/project-ideas.json
Closes #1126 
Added Link for Java projects
=> chore : Added link for Java Projects

database/frontend/colors.json
Closes #1200 
- Added a new color resource named `Pigment` for frontend category.
=> chore: add new color resource for frontend ✨

database/frontend/animations.json
Closes #1222 
Added "hover.css" link to the animation section of LinksHub
=> Added new animation.

database/youtube/game-development.json
Closes #1232 
Added youtube resource for game development
=> Added youtube resource for game development

components/Errorpage/not-found.tsx, pages/[subcategory]/index.tsx
=> [feat] : Error page added

database/frontend/images.json
Closes #1140
I have added an image resource to the website.
=> Add Shutterstock

database/data.ts, database/index.ts, database/ml&ai/ai.json
=> Added : AI Course by Prof. Mausam from IIT Delhi

database/youtube/tensorflow.json
fixes #1252 
Added YouTube Playlist for Tensorflow in the youtube section and under tensorflow subcategory
kindly review this PR under gssoc'23
=> Tensorflow additional data added

README.md
Added gssoc timeline and pointer system used for gssoc'23
=> [DOCS] Add gssoc'23 timeline and pointer system

database/frontend/ui-generators.json
Close #1030 
Added chakra ui in front end (UI generators)
=> Chore:Update ui-generators.json

database/frontend/colors.json
Closes #1039
Paletton links was added to colors category
=> Add Paletton to Colors

components/Header/Header.tsx, components/TopBar/CategoryDescriptions.ts, components/TopBar/TopBar.tsx, components/TopBar/index.ts, pages/[subcategory]/index.tsx, pages/search.tsx
Reverts rupali-codes/LinksHub#1282
=> Revert "fix bug: search query overlaps search result"

pages/contributors.tsx
I have added hover effect to the individual cards, add some border to the images in the cards along with hover effect to the images.
Increased the font size of the contents inside the cards by a few pixels to make it look more prominent.
https://www.awesomescreenshot.com/video/18976128?key=50ca96dffaa23aada0c865e56b2fd196
Subset of pr #1262 
Had trouble pushing more changes on the same branch, so opened a new pr
Added the same styling as I added while making the previous pr along with the changes proposed that was to add margin between the cards.
=> Beautify contributors page

database/youtube/game-development.json
adding one more link to the resouces
Closes #1230
Added one more game dev link
=> added game dev link

database/resources/project-ideas.json
PR fixes an open issue , Closes #1182 
It adds Django projects in project-ideas of resources .
Kindly review this.
=> Added the Django Projects related to issue-1182

components/TopBar/TopBar.tsx, components/TopBar/index.ts
Closes #1306 
- also specify type of function as a standard convention in typescript
- warnings is shown in the issue description
=> refactor: remove index.ts and fix warning

components/SideNavbar/SideNavbarHeader.tsx
Closes #1307 
- warnings shown in the issue description
=> refactor: fix warnings and add type safety

components/SideNavbar/SideNavbarCategoryList.tsx
Closes #1308 
- warnings is shown in the issue description
- remove unnecessary code `router` & `query`
=> fix: warnings and remove unnecessary code

components/popup/index.tsx
Closes #1312 
- warnings shown in the issue description
- In this case, it was just `non-null assertion error`
=> fix: non-null assertion error

components/Aside/Aside.tsx
=> fix: warnings due to any (type) and empty props

components/Footer/Footer.tsx, components/Footer/index.ts
Closes #1317 
- also add attribute in the Link component
- warnings is shown in the issue description
=> refactor: remove index.ts file and fix warning

components/Backdrop/Backdrop.tsx
Closes #1315 
- fix the warnings
=> fix: handle assertion error

components/NewIssue/NewIssue.tsx
=> refactor: use Link component and fix warnings

components/SideNavbar/SideNavbar.tsx
Closes #1310 
- > Fixed
- add `<IContext>` as a type annotation
=> refactor: add type notation and fix warnings

components/Header/Header.tsx
=> fix: warning due to empty props

database/frontend/react.json
Added a tutorial of React Router v6 in Frotend and sub category Reactjs
added this code 
```javascript
{
"name": "React Router v6",
"description": "In this, you'll learn key aspects of React Router, including layout and index routes, nested routes, search parameter filtering, protected routes for authenticated users, and Remix-inspired data router APIs like Loaders and Actions.",
"url": "https://youtu.be/nDGA3km5He4",
"category": "frontend",
"subcategory": "react"
}
```
=> Added React Routes v6 Tutorial

database/languages/javascript.json
=> javaTpoint js tutorial is added

database/frontend/online-code-editors.json
- **Added Interviewbit Object in online-code-editors.json File in frontend Category for Learn and Practice Programming with Different Programming Languages using Online IDE Editor**
- **Additionally, This Interviewbit also Provides Bunch of Topics like DSA, Cheatsheets, Interview Questions**
=> feat: Interviewbit

database/open_source/tools.json
- Added the good first issue tracker tool in the opensource tools subcategory.
=> Added Good First Issues Tool In The Open Source Tools Subcategory 

database/youtube/data-structures.json
=> updated dsa section 

database/resources/blogs.json
- **Added Notion Object Details in `blogs.json` File in `resources` Category** 
- **This `Notion` Website is very Useful for `Writing Blogs, Good Workspace and Other Community Based Features`**
- **This Website very useful and elevates Personal Portfolio gets More Weightage**
=> feat: Notion

database/resources/official-docs.json
- **Added `Node.js Dev Documentation in official-docs.json File in resources category` for Learning Node.js as a Web Developer** 
- **In this Website, Step by Step learning of How to use `Node.js in Both Client Side and Server Side` more concisely**
- **This `Node.js Dev Documentation Website resolves Node.js Related Doubts in Both Client Side and Server Side` Parts**
=> feat: Node.js Official Dev Doc

.dockerignore, Dockerfile, README.md, docker-compose.yml
1. Dockerized version of the app.
2. Changes in the docs to setup the environment.
3. Closes #1159 
*Note: In case you're wondering how the changes reflect the same way if you do it locally, the compose file mounts the current directory directly to the container with `rw` permissions, hence any changes made on any side will reflect to the other.*
=> Feat: Add dockerized linkshub

database/data.ts, database/index.ts, database/languages/dart.json
Closes #1331 
Created subcategory for Dart programming language in the 'Languages' category.
=> Created Dart Subcategory in The Languages Category

database/data.ts
=> chore: fix data-structures typo

components/Cards/Card.tsx, components/Share/Share.tsx, components/Share/index.ts
Closes #1392 
- Added share feature via Web Share API
Uploading LinksHub - Accessibility and 4 more pages - Personal - Microsoft_ Edge 2023-07-27 14-18-13 (1).mp4…
=> feat: added share feature

database/frontend/react.json
Subset of pr #1364 
The pr seemed to be having some conflicts so opened this one, please close the previous one.
Thank you
=> React resources

database/resources/official-docs.json
svelte Documentation are Added in Official Docs in Resources
Closes  #1240  
Official Documentation for svelte is added under Offical Docs Section
=>  Svelte Documentation are Added Under Official Docs  ✨

database/frontend/icons.json
=> chore: Add Free3Dicon to the frontend/icons category.

database/youtube/game-development.json
Closes #1189 
Added Game Development in Vanilla JS youtube [link](https://www.youtube.com/playlist?list=PLYElE_rzEw_sowQGjRdvwh9eAEt62d_Eu)
=> chore: Added Game Resources

database/frontend/images.json
Closes #1245 
I have added a new image resource to the website.
=> Add Dreamstime

database/open_source/blogs.json
Closes #1188 
Added quine resources
https://www.youtube.com/playlist?list=PLnCV5fTAsUgpaLMY_Z8FqPxZ89v-_pcfY
=> chore: Added Quine Resources

pages/[subcategory]/index.tsx, pages/_document.tsx, pages/index.tsx, pages/search.tsx
Closes #1295 
Added meta tags to the website.
=> Added meta tags

database/frontend/online-code-editors.json
=> gfg editor added

database/frontend/colors.json
closes #1430 
-Added Colorspace link to the Frontend colors category.
=> add: colorSpace link to frontend colors category

database/youtube/computer-science.json
Added KNOWLEDGE GATE YouTube channel in database/youtube/computer-science.json
=> added KNOWLEDGE GATE channel computer-science.json

database/other/communities.json
=> ai community added

components/CopyToClipboard/CopyToClipboard.tsx, components/Share/Share.tsx
before
after 
https://github.com/rupali-codes/LinksHub/assets/96341431/e7463e8d-7967-4f58-a6f7-cc84d9e39f61
=> hovering text fixed

database/frontend/online-code-editors.json
Closes Issue No : #1383 
- Added `Sublime Text Online Code Editor in online-code-editors.json File in Frontend Category`
- Sublime Text is a shareware text and source code editor available for Windows, macOS, and Linux. It natively supports many programming languages and markup languages. Users can customize it with themes and expand its functionality with plugins, typically community-built and maintained under free-software licenses.
=> feat: Added Sublime Text Online Code Editor in online-code-editors.json File in Frontend Category

components/Searchbar/Searchbar.tsx
Closes #1378 
`autoComplete="off"`
=> feat: disable autoComplete for searchbar

tsconfig.json
Closes #1334 
```json
"noImplicitAny": true,
"strictNullChecks": true,
```
=> feat: add noImplicitAny & strictNullChecks in tsconfig

database/cloud_computing_platforms/aws.json, database/cloud_computing_platforms/azure.json, database/cloud_computing_platforms/gcp.json, database/cloud_computing_platforms/ibm.json, database/cloud_computing_platforms/oracle.json, database/data.ts, database/index.ts, types/index.ts
=> cloud added

database/youtube/web-development.json
Closes #1340 #1341 #1342 #1343 #1344 
- Added `Web Development Video` Details in `web-development.json` File
- YouTube channels named as `Simplilearn, Intellipaat, EDUREKA(Web Dev), SuperSimpleDev and SCALER`
- ` I have combined 5 Issues related to Web Development  with this PR.`
- `Please Notify Them` @rupali-codes
=> feat: Added Web Development YouTube Video Details in web-development.json File 

database/youtube/testing.json
Closes #1345 #1346 #1347 
- Added `Software Testing Course YouTube Video` details in `testing.js File in youtube Folder`.
- YouTube channels named as `Software Testing Mentor, Automation Step by Step and EDUREKA(Testing)` 
- ` I have linked All related Testing related Issues raised by Me and also combined together with this PR `
- ` Please Notify Them` @rupali-codes
=> feat: Added Software Testing YouTube Videos Details in testing.json File

database/other/communities.json
=> zuno community added

database/open_source/blogs.json
=> open source blog added

pages/_document.tsx
Closes #1461 
- I tried using `next/head`, and resolved as per documentation
- Docs Reference: https://nextjs.org/docs/messages/no-title-in-document-head
- add comments for various parts in `_document.tsx`
=> chore: fix warning as per official docs

database/other/podcasts.json
=> codenewbie podcast added

components/TopBar/CategoryDescriptions.ts, database/DevOps/cicd.json, database/DevOps/devopsLifecycle.json, database/DevOps/devopsMethodologies.json, database/DevOps/docker.json, database/DevOps/kubernetes.json, database/DevOps/microservices.json, database/data.ts, database/index.ts, types/index.ts
Closes #1371 
- Added `DevOps` category
- Added its subcategories
- Added resources for `DevOps` category
- I have made all the necessary changes to the files
- If any changes needed, please let me know
=> feat : Added devops category and links for its resources in subcategories.

database/resources/official-docs.json
#1451 
Add `JSON `data about `Expreejs `
**Kindly Review it And merge it Happy hacking :)**
=>  Add Official Docs for Express  ✨

database/data.ts, database/index.ts, database/open_source/videos.json
Closes #1015  
Closes #1014 
I added a video subcategory to the open source section and a video that provides information about a video that provides advice on becoming an open source maintainer. 
I'm open to feedback.
=> Adding Video subcategory and resource for the open source section

data/maintainersData.ts
=>  maintainer updated

database/other/communities.json
=> aws community added

database/resources/e-book.json
=> bookboon added

database/resources/e-book.json
=> computer books added

database/frontend/animations.json
Closes #1428 
-Added animate.css resource/link in the animations category
=> add: animate.css

database/frontend/images.json
Closes #1497 
I have added a new image resource to the website.
This PR is part of GSSOC'23.
=> Add image resource

database/frontend/icons.json
=> chore: Add Icon-Icons to the frontend/icons category.

components/Searchbar/Searchbar.tsx, components/Share/Share.tsx
Closes #1513 
- Fix all the warnings
- Reference for `aria-role`: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/f0d2ddb65f21278ad29be43fb167a1092287b4b1/docs/rules/aria-role.md
@rupali-codes 
Please merge this as soon as possible.
=> fix: terminal warnings and remove unnecessary code

database/resources/e-book.json
=> bookyard added

database/youtube/web-development.json
=> the coder coder added

database/resources/official-docs.json
Closes #1452 
Add `JSON `data about `Ember.js `
**kindly Review it And merge it happy hacking :)**
=> feat: add official docs of Ember.js⚡

database/competitive_programming/platforms.json, database/data.ts, database/frontend/online-code-editors.json, database/index.ts, types/index.ts
Closes #1250 
Adding Competitive programming  as a category and moving the platforms for the same from online editors to platforms subcategory
=> chore: add competitive programming category

database/resources/official-docs.json
Closes #1453
Add `JSON `data about `Laravel `
**kindly Review it And merge it happy hacking :)**
=> feat: add official docs of Laravel ✨

database/other/podcasts.json
=> Adding Stackoverflow Poadcast

database/cloud_computing_platforms/azure.json
=> microsoft certified added

database/youtube/web-development.json
=> level up tuts added

database/frontend/icons.json
Closes #1510 
I have added a new icon resource to the website.
=> Add The Noun Project

database/other/communities.json
=> vmware added

database/frontend/images.json
=> vector stock added

database/frontend/fonts.json
Closes #1568
I have added a new font resource to the website.
=> Add Adobe Fonts

database/youtube/web-development.json
=> devtip added

database/DevOps/docker.json
Closes #1241 
Added docker resources for DevOps
=> added docker resources

database/competitive_programming/platforms.json
added 2 more most visited and renowned coding platform in the list that will help the Competitive programmers practice and hone their skills.
Closes #1547
=> Coding Ninja & Geek for Geeks Coding platofrm Added

database/data.ts, types/index.ts
Closes #1548 
changed the database file where we were adding the categoried and their respective links also, changed the main categories from where the data is fetched.
now
earlier
=> The Competitive programming dropdown fixed

database/youtube/web-development.json
=> joseph smith added

database/frontend/online-code-editors.json
=> jdoodle added

database/youtube/machine-learning.json
=> chore: added codebasics

database/backend/database.json
- **Added GraphQL Details in database sub category in backend Category**
=> feat: Added GraphQL in backend database Category

database/youtube/computer-science.json
=> neso academy added

database/resources/official-docs.json
Closes #1385 
- **Added Python Official Docs Details in officialdocs Sub Category in resources category.**
=> feat: Added Python Official Docs Details in resources Section

database/frontend/animations.json
Closes #1429 
- Added codrops website to the animations section
=> add:codrops in animations section

database/frontend/images.json
Closes #1569
I have added a new image resource to the website.
=> Add FreeImages

database/languages/golang.json
- **New golang tutorial added by freecodecamp.org**
*I hope this small change will add value to the users and please give suggestions if further edit or modification needed*
=> New golang tutorial added by freecodecamp.org

.devcontainer/devcontainer.json
=> [Added] codespaces auto setup

database/frontend/fonts.json
=> chore: add fontmirror to frontend/fonts category #1598

database/data.ts
=> fix: OTHER-category at the end

database/languages/golang.json
- I have changed the description for `"Learn Go Programming" tutorial by programiz`
**Closes issue id #1613**
```
},
{
"name": "Learn Go Programming",
"description": "This playlist contains all the concepts of Golang along with two mini projects",
"description": "Our Go tutorials will guide you to learn Go Programming one step at a time",
"url": "https://www.programiz.com/golang",
"category": "languages",
"subcategory": "golang"
```
- **`NOTE` :: If you want to modify the description please let me know.**
=> chore: update description of golang resource by programiz

database/frontend/colors.json
=> chore:add-Picular-site-in-color-section

data/maintainersData.ts
Closes #1608 
This pull request adds Anmol's name to the Maintainers section on LinkHub's website.
=> feat: add Anmol to maintainer list

database/youtube/software-testing.json
Closes #1636 
Replaced with correct URL
=> fix: replaced with correct URL

components/Footer/Footer.tsx
To optimise for smaller devices, the font size for the copyright section has been reduced.
#1625
=> Reduced the fontSize for the small devices

database/frontend/online-code-editors.json, database/other/other-resources.json
#1302 
Added "Edabit" to the CodeEditors in website
=> feat: add "Edabit"

components/TopBar/CategoryDescriptions.ts
Closes #1639 
I added a description to the icon that’s near the Contributors' title. It’ll help people who are new to LinksHub gain a better understanding of our roles.
[Contributors' description](https://github.com/rupali-codes/LinksHub/assets/105683440/ae673802-7372-4a9e-ba63-e2c74c7b3daa)
=> feat: add description of contributors

CONTRIBUTING.md
Closes #1612 
This PR adds a number chart and a few revisions. This addition would help new contributors, especially those who are new to open source and tech, have an idea of how they can contribute to LinksHub's project.  
I need help with hyperlinking the number chart in line 141.
=> feat: adding chart

database/frontend/react.json
Closes #1623
Added Odin Project link
In the issue I had selected the wrong subcategory "fonts" while I should have selected "React Js"
=> Added Odin Project

database/frontend/online-code-editors.json
Added CodinGame Website Link for Practice & Learn Programming with Interactive Challenges
=> Added CodinGame

database/youtube/machine-learning.json
=> I have added a new link to the machine-learning.json file.

database/data.ts
=> FIX: Card not displaying 

SECURITY.md
Closes #1667 
Replaced linkshub.vercel.app with linskhub.dev in SECURITY.md
=> chore: replaced linkshub.vercel.app with linskhub.dev in SECURITY.md

pages/[category]/index.tsx
=> Updated the tags-color when they are hovered

database/frontend/ui-generators.json
… Thu Sep 14 23:42:52 CDT 2023
Closes  #1665
=> [Added] Adding 3D CSS editor to UI Generators sub-category in frontend

components/Footer/Footer.tsx
Closes #1625
Reduce copyright font size for small screens
=> chore: Reduce copyright font-size for small screens

database/frontend/colors.json
Closes #1677
Added [huetiful-js](https://github.com/prjctimg/huetiful) to the Frontend category under the "colors" subcategory
=> [Add] huetiful-js 

CONTRIBUTING.md, README.md
closes #1678
* added setup guidelines in contributing.md
* removed setup guidelines from readme.md
* added emojis in headings
* fixed typos
Please let me know if any changes required!
=> chore: added setup guidelines in contributing.md file

components/SocialMedia/SocialMediaIconsList.tsx
Closes #1680 
Fixed the header links alignment by tweaking HTML elements hierarchy.
Kindly let me know if any changes are required. Open to suggestions
=> Fix incorrect alignment of header links

README.md
Added Codespaces link in the readme
#1672
=> Added Codespaces link in the readme

database/backend/system-design.json, database/backend/testing.json, database/backend/validation.json, database/cloud_computing_platforms/aws.json, database/open_source/projects.json
I have added new resources in the following categories
- System design
- Testing
- Cloud computing
- Open-source projects
=> chore: added new resources in multiple categories

database/open_source/projects.json
Closes #1695 
I've changed the name of the open-source project from LinkFree to BioDrop.
=> Update: LinkFree to BioDrop

database/open_source/projects.json
Closes #1705 
I've rectified the spelling of "Codecademy."
=> fix: Typo Codecademy

database/backend/api.json
Closes #1714 
- Adds The Razor Pay resource to the api resources section.
=> Added RazorPay api link

components/SideNavbar/SideNavbarElement.tsx
#1687 
Made the Selected category in sidebar highlighted by adding extra adding a path  variable
Please check 
@Anmol-Baranwal @CBID2
=> Fix : selected subcategory in the sidebar

database/frontend/images.json
=> added negative space for stock images

database/open_source/projects.json
=> added rocket chat

database/resources/project-ideas.json
Closes #1748 
It adds C# projects in project-ideas of resources .
Kindly add the hactoberfest accepted label.
=> feat: Add C# Projects in resources category

database/frontend/ui-generators.json
I've added **Mamba UI** on the Frontend sub-category UI Generators list. To do this all I've to do is add the object of Mamba UI 
in **Database/Frontend/ui-generators.json** file.In the screenshot section, I've added both the code screenshot and the preview of the MambaUI card for Review.
=> feat: add Mamba UI on Ui generators

database/languages/cpp.json
Closes #1758 
This PR will fix CPP content not found.
=> fix: cpp-content

database/open_source/projects.json, database/youtube/web3-metaverse.json
Closes #1760 
I have added Patric Collins' YouTube channel to the project.
I am taking part in Hacktoberfest 2023, kindly include the corresponding label.
=> Add: Patrick Collins Yt

database/frontend/next.json
Closes #1761
adding t3 into nextjs sub category
sorry for the previous mess
=> adding t3 into nextjs sub category

database/frontend/icons.json
=> add: remix icon

database/youtube/game-development.json
Closes #1783 
It adds Unreal Sensei-Mega Tutorials Playlist in the game-development category.
Kindly add the hactoberfest accepted label.
=> feat: Add Unreal Sensei-Mega Tutorials Playlist in the game-development category

database/languages/rust.json
Closes #1788 
Add rustlings to the Rust category
Hacktoberfest
=> add: Rustlings (rust)

components/Searchbar/Searchbar.tsx, components/SideNavbar/SideNavbarBody.tsx, hooks/useSearchShortcut.tsx
Solved : [Feature] Adding a quicksearch shortcut. #1781 
Closes #1781 
Made a custom hook  called useSearchShortcut that helps focusing the input field for quicksearch on an input command "/".
=> added '/' as search shortcut

components/Pagination/Pagination.tsx, database/resources/official-docs.json
- Capitalised Svelte spelling
- Updated Python heading by removing the (Offical docs) from it
- Updated React link with more recent URL
- Pagination layout problem solved
Centred on all resolutions
=> Spelling, Heading, Pagination btn and URL updated

database/competitive_programming/cp-tutorials.json
Closes #1794 
Added new tutorial link in Category : Competitive Programming , Sub Category : Tutorials.
Hacktoberfest
=> feat: added new youtube channel link(CodeNcode) in competitive programming tutorials

database/other/other-resources.json
=> added remote job finder resource

database/youtube/tensorflow.json
This PR adds a link to the YouTube channel of @AAmini in the YouTube category of the TensorFlow Subcategory of the project.
- Added a link to the YouTube channel of @AAmini.
=> chore:Added New Link(1768)

database/frontend/icons.json
=> add: eva icons

database/frontend/online-code-editors.json
Closes #1797 
Added JSitor link in online-code-editor database under Frontend category.
=> [Add] Added JSitor in online-code-editor database under Frontend category

database/backend/authentication.json
=> Added clerk to auth

components/SideNavbar/SideNavbar.tsx, tailwind.config.js
Closes #1806
Made the sidebar responsive by adding a new media-query
None
=> Fix1806 sidebar responsive

components/SideNavbar/SideNavbar.tsx, components/SocialMedia/SocialMediaIconsList.tsx, database/backend/authentication.json
Fix the sidebar icons alignment bug
Closes #1812
=> Fix icons sidebar bug

database/frontend/icons.json
Closes #1824 
Added a link in Icons section
Would love to add more contributions.
=> Adding link in Icons section

database/frontend/icons.json, pnpm-lock.yaml
closes #1822 
Added the link as another object in `database/frontend/icons.json`
=> Add lucide icons link

database/backend/authentication.json
=> Added Kinde auth

database/artificial_intelligence/artificial-intelligence.json
Fixes #1836 
I have added the Hugging face into the database of the Ai category and validated the JSON too.
=> add Hugging Face in AI category

database/backend/testing.json
closes #1873
a) Added links to Postman and Cypress resources in the "Testing" subcategory of the backend.
b) Updated the subcategory's content to include brief descriptions of Postman and Cypress.
c) Ensured that the new links are well-formatted and functional.
d) Organized the subcategory to maintain consistency with existing resources.
e) Verified that the links accurately direct users to the relevant Postman and Cypress resources.
=> added postman and cypress to testing/backend

database/resources/project-ideas.json
Closes #1868 
Added a new link under Project Ideas subcategory
This will also be a great addition to the resources.
=> [Add] Flask Project Ideas(#1868)

database/competitive_programming/cp-platforms.json
#1842 
Closes #1842 
Added CodeChef platform to the Competitive Programming db
=> Added Codechef to competitive programming

database/backend/api.json
Closes #1816
this PR adds the recipe search API for the developers who are working on health or food related projects
i have added the link, description and necessary items in api.json, the link is working and good for merging. Thanks
=> added recipe search API

database/backend/authentication.json
Closes #1864 
Keycloak is a authentication service provider.
Adding this in category - `Backend`,  sub-category- `Authentication`
=> Adding keycloak

CONTRIBUTING.md, database/frontend/design-inspirations.json, database/frontend/ui-generators.json
=> fixing the spelling mistakes

components/TopBar/CategoryDescriptions.ts, database/frontend/ui-generators.json
Closes #1820
I've added descriptions for some Frontend subcategories those doesn't have any description before. 
**The categories are: ThreeJs, NextJs, Online code editors, UI generators**
=> Add description

.github/ISSUE_TEMPLATE/add_link.yml
closes #1710
i've added technical writing to the dropdown menu, if any other changes required please let me know
=> added technical writing

database/backend/authentication.json, database/resources/hosting.json
Added brimble to resources - hosting
Closes #1834
=> chore: added Brimble

database/open_source/projects.json
Fixes #1835 
I have added the Hugging face into the database of the Ai category and validated the JSON too.
Kindly add the hacktoberfest-accepted label too. @Anmol-Baranwal @CBID2
=> add: The Tor Project in Open-Source/Projects

database/technical-writing/tools.json
Closes #1877 
Added https://app.grammarly.com/ links to the Technical Writing Category 
Ensured that the new links are well formatted.
=> chore: add grammarly in technical writing #1877

database/frontend/animations.json
Closes #1751 
New Animation - React Spring
=> [add] Animation: react spring

database/other/communities.json
Closes #1821 
It adds Women Who Code in the communities category.
Kindly add the hactoberfest accepted label.
=> feat: Add Women Who Code in the communities category

README.md
Closes #1894
Added social media icons in the Socials  section of README.md to make it look more appealing.
before:
After:
=> [DOCS] : Added Social Media icons in README.md

database/languages/cpp.json
Closes #1893 
added a new link under languages category
This would be a great addition to the resources
=>  chore : added C++ and DSA course

database/backend/testing.json
Added hoppscotch to testing
Closes #1885
=> chore: added hoppscotch

database/technical-writing/tools.json
#1878 
Closes #1878 
Added Hemingway editor in the technical writing tools section
=> Chore: added technical writing tools

components/SideNavbar/SideNavbarElement.tsx
Closes #1757 
I have made the menu auto closing. I created a issues as adding a new feature but in the code I checked later that the feature is already implemented but there was a small bug due to which it was not working. Hence, I fixed that.
=> Auto close menu

database/backend/database.json
Closes #1901 
New Database - MariaDB
=> Add new Database - mariaDB

README.md
Closes #1703 
@CBID2 
Please check the changes.
=> chore: add Hacktoberfest in Outreach section

README.md
Fixes #1920 
Updating twitter id link in README.md
Before : https://twitter.com/the_linkshub
After : https://twitter.com/linkshubdotdev
=> [Fix] Updating twitter id link 

database/competitive_programming/cp-tutorials.json
#1911
Closes #1911
Added Youtube tutorial link in the Competitive Programming Tutorials Section
=> Chore: Added tutorial link in Competitive Programming Tutorials

database/devops/docker.json
Fix issue #1888 
Add Docker documentation to learn docker
=> add-docker-docs

database/resources/project-ideas.json
Closes #1912 
It adds Cyber Security projects in project-ideas of resources .
Kindly add the hactoberfest accepted label.
=> feat: Add Cyber Security Projects in resources category

database/frontend/react.json
Closes #1944
Added a Redux Toolkit in english tutorial link.
I haven't set it up locally; I just added the link.
Please consider merging this pull request.
=> add redux tutorial link 

database/languages/javascript.json
##Proposed Changes
Add new javascript link
Closes #1942
I did't set it up locally, just add the link. 
Kindly add this PR.
=> Added new javascript tutorial link

database/youtube/css.json
closes #1935
Added YouTube Playlist for in depth tutorial on CSS in hindi language
=> chore: Add Hindi CSS YouTube Playlist (#1935)

database/frontend/colors.json
closes #1924
a) Added links of Realtime Colors  to "Colors"  subcategory of the frontend.
b) Updated the subcategory's content to include brief descriptions of Realtime Colors .
c) Ensured that the new links are well-formatted and functional.
d) Organized the subcategory to maintain consistency with existing resources.
e) Verified that the links accurately direct users to the relevant Realtime Colors resources.
=> added Realtime Colors to Colors/Frontend

database/youtube/css.json, database/youtube/web-development.json
Closes #1929 
Add New Link On Css Course Youtube Playlist
Im first time contribute on LinksHub if make any mistake or need any change please report me. Thanks
=> add css course

database/languages/cpp.json
Closes #1958
Added CPP playlist
=> Added CPP playlist to cpp.json

components/TopBar/CategoryDescriptions.ts, database/data.ts, database/index.ts, database/resources/dsa.json
Closes #1959 
Added DSA subcategory under Resources category.
##
It will be great addition to the resources.
=> chore : Added Dsa subcategory under Resources category.

database/other/roadmaps.json
closes #1939 
Kindly look into the PR and please let me know if any further change is needed
=> add dsa roadmap in category other under roadmaps

components/TopBar/CategoryDescriptions.ts, database/DSA/DSAarticles.json, database/data.ts, database/index.ts, types/index.ts
Closes #1890 
Added DSA as a new category and subcategory - DSA-articles.
=> Added DSA category

database/competitive_programming/cp-platforms.json
- Added Exercism Coding platform to Competitive Platform Category .
Closes #1969 
- Updated cp-platforms.json file
- If I need to update anything Do let me know.
=> feat: Add exercism to CP platform category (#1969)

components/TopBar/CategoryDescriptions.ts, database/data.ts, database/devops/jenkins.json, database/index.ts
Closes #1931 
LOL! I created this myself.
=> chore: add jenkins subcategory in DevOps

database/backend/system-design.json
Closes #1984 
Add System Design Primer Github Repo.
=> Add : System design primer

database/frontend/animations.json
Closes #1983 
Add New Animation Library called **GSAP** in the **frontend** category and **animations** subcategory.
=> Add GSAP Animation Library in animation.json

database/backend/database.json
closes #1998 
I have listed Apache's Cassandra DB in Databases of Backend category with description.
[![JFqenqB.md.png](https://iili.io/JFqenqB.md.png)](https://freeimage.host/i/JFqenqB)
=> feat: add cassandra db to database.json

README.md
=> chore: replace broken link with new discord icon source

database/data.ts, database/index.ts, database/other/domains.json
=> chore: add domain category

components/SideNavbar/SideNavbarBody.tsx
Closes #2022 
- Removed unwanted Tailwind Utility classes for Transition which has been applied for SideNavbar.
|BEFORE|AFTER|
|:--:|:---:|
|![BEFORE](https://github.com/rupali-codes/LinksHub/assets/92252895/58acb31a-5869-49c2-a2a3-47d817f61970)|![AFTER](https://github.com/rupali-codes/LinksHub/assets/92252895/36c20e6b-5823-4f05-a40a-64a38e9f3168)|
=> fix: laggy navbar transition during theme toggle 🛠️✨ 

database/languages/cpp.json
Closes #2006 
LinksHub is a valuable resource for developers seeking to expand their knowledge on various programming topics. In line with this mission, I propose adding a video link related to the C++ Standard Template Library (STL) to enhance the project's content.
- The C++ STL is a fundamental component of the language, and developers often seek resources to improve their understanding.
- The video covers important topics or concepts not currently addressed in the project.
- It enhances the project's comprehensiveness and value to the developer community.
I welcome feedback and suggestions from maintainers and contributors regarding this proposed addition. Let's collaborate to ensure that this enhancement aligns with the project's goals and standards.
Please let me know if there are …
=> Added C++ STL Video Link

database/open_source/os-tutorials.json
Closes #2012
Added Youtube link for complete Open Source BootCamp in Hindi
This is My first PR to this repo, please review it and give me Feedback
=> [Added] Open Source Tutorial Link Added

database/open_source/projects.json
Closes #2011 
Added:
- DevProfiles - https://devprofiles.is-an.app
- DevTweet - https://devtweet.is-an.app
=> chore: add open source projects

components/TopBar/CategoryDescriptions.ts, database/data.ts, database/index.ts, database/open_source/os-programs.json
fixes #2004
added a sub category 'os programs' to the open-source heading
updated the index.ts, data.ts, CategoryDescriptions.ts, created an os-programs.json file in the open-source dir of the database folder.
@Anmol-Baranwal  thank you for assigning this issue to me :-)
=> os-programs sub cat added open-source dir #2004

database/open_source/projects.json
Closes #1997 
Add Free Programming Books Github Repo.
=> add: Free Programming Books to projects open source

database/backend/database.json
Closes #1995 
Add a new link of Robust, Modern, Scalable My-SQL based Database Platform called **PlanetScale.**
=> Add PlanetScale Database

database/frontend/themes-templates.json
Closes #2027 
Added Themesberg to Themes&Templates section under Frontend Section.
I am open to any suggestions regarding this PR.
=> Added ThemesBerg to Themes&Templates under Frontend Section

database/backend/database.json
- Added Neon DB to into Database sub-category of Backend Category
Fixes #2023 
- updated database.json
=> added neon db to database.json

database/youtube/machine-learning.json
Closes #2039 
Added a new Machine Learning Resource from Youtube
=> Add: New ML Learning resource

database/cybersecurity/offensive_security.json
Fixes #2017 
Added zSecurity under cybersecurity category
=> add: zSecurity under cybersecurity category

database/youtube/web-development.json
fixes #2018
Added Chai and Code Youtube channel
=> added Chai and Code youtube channel for webdev #hacktoberfest2023

CONTRIBUTING.md, components/TopBar/CategoryDescriptions.ts, database/data.ts, database/index.ts, database/languages/solidity.json
Closes #1771 
1. Added subcategory solidity with links to some of the best resources
2. Made changes following CONTRIBUTING.md
3. Added an ending curly brace on line 207 of CONTRIBUTING.md
Hello, this is my first ever open source contribution. I am open to conversation for any other changes required if any. Thank You.
=> Added solidity as a subcategory

database/open_source/os-tutorials.json
Closes #2055 
Added new link to category : Open source, sub-category : tutorials
=> chore:Add new tutorial to open source (#2055)

components/TopBar/CategoryDescriptions.ts, database/data.ts, database/index.ts, database/other/git.json, pnpm-lock.yaml
closes #2030 
Added 3 resources to learn about git
=> feat: added the resources for learning git

database/frontend/react.json
Closes #2068
Added Free certificate course Introduction to frontend by META
=> Added frontend course by META

database/youtube/web3-metaverse.json
Closes #2054
Added a new resource link in web3-metaverse.json
=> Added a new resource link in database/youtube/web3-metaverse.json

database/frontend/colors.json
Closes: #2003
Added UiColors to Colors section under Frontend Section
I am open to any suggestions regarding this PR.
=> add: UIColors to Colors under Frontend Section

database/languages/cpp.json
Closes #2040 
Added new c++ course to the category : language sub-category : c++
=> chore:Add new link to c++(#2040)

database/other/roadmaps.json
Closes #2101 
Added the blockchain roadmap
=> Added <Blockchain roadmap>

CONTRIBUTING.md
Closes #2111
Fixed the formatting of some of the commit message examples in the contributing guidelines.
=> docs: fix formatting issues in CONTRIBUTING.md

database/youtube/web-development.json
Closes #2096
- Adding Hitesh Sir's YouTube Channel
Thank You this is a amazing resource
=> Adding Hitesh Sir's YouTube Channel

database/backend/database.json
Add New Database Named YugabyteDB
Closes #2109 
Add New Database Called **YugabyteDB** in the backend section.
=> Add Yugabyte DB database

database/frontend/ui-libraries.json
fixes : #2126 
New UI Library NEXT UI added to the database of frontend ui- libraries
=> chore: nextui added to frontend ui-librariries

database/cybersecurity/offensive_security.json
Closes #2075
- I have updated the repo with an awesome and needful resource which is a whole database of publicly available exploits.
- This database is from offensive security.
According to my experience, this is a mandatory resource for cybersecurity geeks. It helps them to know more about the technical aspects of the vulnerabilities by analysing the exploits.
=> Added exploitDB resource

database/open_source/articles.json, database/open_source/os-programs.json
closes #2134  
This PR adds MLH to the open source programs category.
=> feat: add MLH fellowship to open source programs

database/other/roadmaps.json
Closes #2118 
Added the python roadmap
@Anmol-Baranwal @CBID2 Review please
=> Added Python roadmap

database/DSA/DSAYouTube.json
Closes #2037 
Added a YouTube sub category under DSA category and added a YouTube playlist.
=> Added a YouTube sub category under DSA category and added a YouTube playlist.

database/frontend/ui-generators.json
Fixes #2131 
ui-generators.json
=> added Shadcn Ui to frontend Ui genrators

database/data_structures/dsa-tutorials.json
closes #2152 
please merge this request under hacktoberfest label
=> Added DSA youtube playlist - Dataflair

database/resources/dsa.json
closes #2079 
Added Strivers 79 Last Moment DSA Sheet to category : resources, sub-category : dsa
=> chore:added striver's 79 dsa cheatsheet

database/youtube/web-development.json
=> Added new course

pages/[category]/[...subcategory].tsx
fixes #2153
Minor style changes in the component `[...subcategory].tsx`
=> fix/2153 div-overlap

components/TopBar/CategoryDescriptions.ts, database/data.ts, database/index.ts, database/languages/swift.json
Closes #2148 
- Add Sub Category in `data.ts` , `index.ts`
- Create swift.json
- Added Sub Category Description For Swift in CategoryDescriptions.ts
Suggest any required changes!!
Thank You.
=> feat: Add Swift Sub Category

database/frontend/animations.json
Closes #2163 
Add easings.net in frontend/animations
=> chore: Add Easings in animations subcategory

database/frontend/icons.json
=> feat: add iconsax icon

components/SideNavbar/SideNavbar.tsx
Closes #2069 
Made modification in the code.
@Anmol-Baranwal Can you review the PR.
=> [RESOLVED]: Sidebar not scrolling upto bottom in mobile devices 

database/other/podcasts.json
Closes #2136 
Through this PR, I have added about two amazing Podcasts: Overpowered and WVFRM.
=> Added a Podcast resources

database/resources/project-ideas.json
=> Added a new project idea (Web development) in the project-ideas.json

database/placement_prep/resume-building.json
=> Added a card in the resume builder - (Overleaf) .

database/technical-writing/tools.json
Closes #2212
This PR adds Docusaurus to the Technical writing tools section.
=> feat: add Docusaurus

database/frontend/react.json
Closes ##2221
Add the Mantine link in the frontend category.
=> feat: Added mantine link in frontend category

database/other/roadmaps.json
added `roadmap.sh` in other/roadmaps category
=> chore: added roadmaps.sh in other/roadmaps"

database/data.ts, database/frontend/angular.json, database/index.ts
Closes #2227 
Addin new Angular subcategory with resources under Frontend category
=> feat: Angular - New Subcategory under Frontend

components/popup/popupInfo.tsx
This PR closes #2230 
Added margin for the copytoclipboard button
=> fix copytoclipboard button gap issue #2230

README.md, pages/index.tsx
Closes #2217 
This PR is an improved version of PR #2219. Check its Changes Proposed section for context.
=> feat: update slogan

.github/workflows/repo-rater.yml
Closes #2225 
This PR adds the Repo-Rater GitHub Action, which encourages contributors to rate their experience with our project on [Repo-Rater](https://repo-rater.eddiehub.io/). It'll help the project gain more visibility.  
I tested this GitHub Action in a [test repo](https://github.com/CBID2/test-for-repo-rater/pull/1). Below is a screenshot of the result:
=> feat: add Repo-rater GitHub Action

components/TopBar/CategoryDescriptions.ts, database/competitive_programming/cp-helpers.json, database/data.ts, database/index.ts
closes #2206
added digitomize link in the
category -> Competitive Programming
subcategory -> Helpers
=> chore: add link digitomize in cp/cp-helpers

components/Breadcrumps/index.tsx, components/Searchbar/Searchbar.tsx, components/TopBar/TopBar.tsx
Closes #2246 
fix bug  search query value in breadcrumbs
=> #2246 fix search query value in breadcrumbs

components/Sidebar/Sidebar.tsx
Closes #2266 
fixed the sidebar scrolling issue
=> Fix: [BUG] Sidebar not scrolling properly

database/other/devtools.json
#2277
Add new devtool item **[Dr Link Check](https://www.drlinkcheck.com/)**
=> Add Dr Link Check

database/languages/javascript.json
Added You Don't Know JS Yet series
=> chore: Added new resource in javascript

database/placement_prep/job-portals.json
Closes #2271 
It's a platform that helps you get the job and place the job
=> naukri-link-added

database/cybersecurity/defensive_security.json, database/cybersecurity/malware_analysis.json, database/cybersecurity/web_application_security.json, database/frontend/ui-generators.json
Fixed the broken links, by either updating them or putting any other alternative.
=> Fixed the broken links

database/frontend/ui-libraries.json
#2268
- Add Float UI 
- Fix subcategory for Material Tailwind
=> Add Float UI

database/placement_prep/job-portals.json
Closes #2290 
It is the best platform to get the job and preparation for job interview.
=> freshersworld-added

database/placement_prep/job-portals.json
Closes #2295 
added worksatastartup link in sub-category of job-portals in the category of placement-prep
=> Closes #2295 [add] work at a startup link

database/backend/testing.json, database/other/roadmaps.json, database/placement_prep/job-portals.json
Closes #2313 
Spelling Updates
1. Backned to Backend
2. Fronted to Frontend
3. LinkdedIn to LinkedIn
4. plaform to platform
Adding i18n localization for multi-language support will be a nice option, if you guy's agree please let me know.
=> Closes #2313 - Spelling Mistakes

database/cybersecurity/web_application_security.json
fixes #2287 
Add Trivy & Snyk to **cyber-security / Web Security** 
I only add those two but prettier indented the entire file.
```json
{
"name": "Trivy",
"description": "Trivy is the most popular open source security scanner, reliable, fast, and easy to use. It's a container security scanner designed specifically for Docker images.",
"url": "https://trivy.dev",
"category": "cyber-security",
"subcategory": "web-security"
},
{
"name": "Snyk",
"description": "Snyk specializes in JavaScript security. It is a developer-first security solution that helps you use open source code and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.",
"url": "https://snyk.io/",
"category": "cyber-security",
"subcategory": "web-security"
}
```
=> Add Trivy & Snyk

database/languages/rust.json
Closes #2324 
added link to Actix web framework on languages/Rust
added link to Bevy Game engine on languages/Rust
=> add links to rust on languages/rust

database/open_source/projects.json
fixes #2333
Add Free For Geeks in open-source/projects
```json
// projects.json
{
"name": "Free For Geeks",
"description": "Free For Geeks is your curated toolbox for building better software. Free resources for all your dev needs.",
"url": "https://freeforgeeks.com/",
"category": "open-source",
"subcategory": "projects"
}
```
=> [Add] Free For Geeks

CODE_OF_CONDUCT.md
fixes #2325
The Code of conduct now has @rupali-codes email: [rupali.codes@gmail.com](http://rupali.codes@gmail.com/)
=> ADD email in CODE_OF_CONDUCT.md

components/Breadcrumbs/index.tsx, components/Cards/Card.tsx, components/CopyToClipboard/CopyToClipboard.tsx, components/Footer/Footer.tsx, components/Searchbar/Searchbar.tsx, components/TopBar/TopBar.tsx, components/popup/popupInfo.tsx, layouts/GeneralLayout.tsx, pages/[category]/index.tsx, pages/index.tsx
closes #2247 
- I've improved the styling of various sections for both the dark and light themes. 
- You can use this overview to check the live changes. I've attached it for reference.
> Dark theme
| Old | New |
|--------|--------|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/93cceac2-1adf-4e00-9a63-abcd2772a66f) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/14854997-88e7-436b-b47f-8917ba2505d6) |
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/162993ef-6e88-4228-aba6-785734dabd4c) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3caf32a4-6f51-457a-ad0b-673a8a8c6bd0) |
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/0b97bd00-8c08-4041-a7d1-d508c3508b15) | …
=> feat: improve styling of various sections for light and dark theme

database/backend/testing.json
fixes #2337
Add [playwright](https://playwright.dev/)
Category: Backend
Sub Category: Testing
=> Add playwright

database/backend/authentication.json
Closes #2352
Added Corbado, a passkey-first authentication provider, to backend > authentication.
=> feat: Added Corbado to backend>authentication

CONTRIBUTING.md
Since people now have the option to click on the "Wanna Share Something" button to suggest new categories, I slightly adjusted **[line 107 in the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/bb98806320c7108566f4af6a08436b226b7f1b21/CONTRIBUTING.md?plain=1#L107C1-L108C1) so they can see this option.  
Closes #2348 
I changed [line 107 in the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/bb98806320c7108566f4af6a08436b226b7f1b21/CONTRIBUTING.md?plain=1#L107C1-L108C1).
=> docs: adjusting the step to suggesting new categories

database/open_source/projects.json
fixes #2368
[Add] [ProductiveHub](https://www.productive-hub.com/) in category: Open Source, sub category: projects
=> [Add] ProductiveHub

database/youtube/computer-science.json
Closes #2372 
Added Arpit Bhayani to youtube/computer-science
Site URL
https://www.youtube.com/@AsliEngineering
Description
Arpit Bhayani's YouTube channel explores diverse computer science topics including databases, system design, architecture, and algorithms.
=> Add Arpit Bhayani to youtube/computer-science

database/languages/rust.json
closes #2375 
Added new course called `Rustlings Infinity` in database/languages 
cc : @rupali-codes @CBID2 @Anmol-Baranwal
=> (chore) : Add Rust Infinity in database/languages

database/backend/testing.json
=> Yaak added in Backend Testing

database/other/devtools.json
=> [Delete] duplicate Postman

database/backend/api.json, pnpm-lock.yaml
Added a new Api to the api section in backend
i have added a sceenshot of code as well as changes reflected in UI
=> feat(backend/api): add new Api to Api list (#2364)

database/other/devtools.json
**Closes #2414**
Added new Resource for Dev Tools
=> feat: Added New Resource of Dracula Theme (#2414)

database/frontend/icons.json
=> Iconse feature added

styles/globals.css
Closes issue #2412 
Background-color for selection changed to purple, as discussed in issue #2412.
=> feat: changes backgound-color at ::selection attribute

pages/index.tsx
Closes #2409 
- Added a background color transition effect to the buttons on the main page to enhance user experience.
- Implemented dynamic styling for hover effects using inline styles with React `useState` for managing hover state.
- Ensured smooth transitions with a duration of 0.3s using the `transition` CSS property.
- on hover:
Please review the hover effects added to the buttons on the main page. The background color transitions should provide a smooth visual feedback when hovered over.
=> Added hover effect on buttons of main page

database/ai_tools/design.json
=> [Add] TOOOLS.design

pages/[category]/index.tsx, pages/index.tsx
Closes #2442 
Removed duplicate Tailwind classnames in pages.
=> fix: Remove duplicate Tailwind classnames (#2442)

database/youtube/computer_science.json
=> [Add] university academy link

database/youtube/computer_science.json
Closes #2443
Adds a new link: https://www.youtube.com/playlist?list=PLu0W_9lII9ajkincuKn6f6tIk76l5Suqw, titled "Revising X in Y Minutes - CodeWithHarry" under Youtube/Computer Science
=> chore(new link): Revising X in Y minutes

database/youtube/web_development.json
=> [Add] Youtube channel - Theo.gg

database/languages/python.json
Closes #2451
Adds a new link: Tech With Tim under `languages/python`
=> chore(new link): add Tech With Tim

CONTRIBUTING.md, database/ai_tools/design.json, database/cybersecurity/web_application_security.json, database/frontend/colors.json, database/frontend/design_inspiration.json, database/other/communities.json, database/resources/blogs.json, database/resources/e_book.json, database/youtube/web3_metaverse.json, database/youtube/web_development.json
Closes #2437 
Removed the broken links from database
=> fix: remove broken links

database/frontend/design_inspiration.json
=> [Add] Awesome-Design-Tools

database/backend/email_providers.json
=> resolving conflicts (#2420)

components/Cards/Card.tsx
Add background and border for resource card
I hope i did everything right. If not, I am eager to fix it.
=> chore: Add background and border for resource card (#2463)

components/SideNavbar/SideNavbarCategory.tsx
Closes #2445
Capitalize YouTube correctly in sidebar
=> Fix: Capitalize YouTube correctly in sidebar (#2445)

database/frontend/ui_libraries.json
Closes #2431
Adds a new link: Indie UI
=> chore(new-link): Indie UI

.github/workflows/compliance.yml
Closes #2389 
This PR adds a workflow that warns contributors that the form for the Pull Request(s) is not fulfilled, encouraging them to create more effective PRs.   
> [!NOTE]
The screenshots shown are from repo that I created. I decided to do this to ensure that it works before submitting it to the LinksHub repo.
=> feat: add pull request compliance workflow

database/cybersecurity/malware_analysis.json
- Add link to Click Here podcast
- Fix category for Any Here link
=> chore: Add Click Here link

database/other/podcasts.json
Closes #2477 
Add Darknet Diaries link
category : others
Subcategory : Podcasts
=> chore: add darknet diaries (2477)

database/other/podcasts.json
=> chore: Add Syntax

database/other/podcasts.json
=> chore: Add The Junior Jobs Podcast

database/frontend/ui_libraries.json
closes #2492 
-  adds a new link in the UI libraries sub-category inside frontend category
=> chore: Update ui_libraries.json

database/backend/api.json
Closes #2493 
Added the ISRO API in the backend category and api subcategory
Kindly review the PR.
=> added link

database/other/other_resources.json
#2495 
Adds a new link: PigmentTS
=> chore: new link pigment-ts

database/languages/general_web_fundamentals.json
-fix bug
The Broken link of the Language/general_web_fundamental/hitesh choudhary youtube is been fixed 
Changes made is 
Before fix link is : https://www.youtube.com/@HiteshChoudharydotcom
After Link fix : https://www.youtube.com/@HiteshCodeLab
=> fix: the Broken link of Language/general_web_fundamental/hitesh choudhary youtube

database/artificial_intelligence/artificial_intelligence.json
Closes #2511
Add MemFree under Artificial Intelligence
=> feat: add memfree

database/artificial_intelligence/artificial_intelligence.json, database/open_source/tools.json
Tool which is a developer resource platform featuring a categorized collection of tools and resources.
Added this tool which is made for the developer resource platform.
=> feat: add hubdev

database/other/devtools.json
Closes #2509
Added Uptime Kuma under Dev Tools
=> feat: add uptime-kuma

database/resources/e_book.json
closes #2552
add Anna's Archive link
=> feat(resources): Add Anna's Archive link to Resources/E-books 

database/placement_prep/cover_letters.json, database/placement_prep/portfolio_building.json, database/placement_prep/resume_building.json
closes #2564 
Add FlowCv website Link to Cover Letters
=> feat: added links for resume building

database/frontend/online_code_editors.json
Closes #2571 
added new object in database/frontend/online_code_editors.json
=> feat: add project idx as a new link in  frontend / online_code_editors

.github/ISSUE_TEMPLATE/add_link.yml
Closes #2595 
- Mobile
- CMS Toolkit
- Design
- AI Tools
- Tech Articles
- Newsletters
- Theory Of Computation
- Quality Assurance
- Game Development
- Ethical Hacking
- Machine Learning
- Youtube
=> refactor: updated category names

database/ai_tools/chat_bots.json, database/ai_tools/design.json, database/frontend/react.json, database/languages/javascript.json
[Closes #2490 ](https://github.com/rupali-codes/LinksHub/issues/2490#issue-2513903893)
- [ERROR] https://devmesh.intel.com/member-programs/intel-student-ambassador-program | Failed: Network error: error sending request for url (https://devmesh.intel.com/member-programs/intel-student-ambassador-program)
- [403] https://openai.com/chatgpt/ | Failed: Network error: Forbidden
- [403] https://stock.adobe.com/in/ | Failed: Network error: Forbidden
- [404] https://uizad.com/ai-design/ | Failed: Network error: Not Found
- [TIMEOUT] https://www.adobe.com/in/products/firefly.html | Timeout
- [521] https://scrimba.com/learn/learnreact# | Failed: Network error: Unknown status code
- [521] https://scrimba.com/learn/learnjavascript | Failed: Network error: Unknown status code
- …
=> fix: document links fix

database/ai_tools/chat_bots.json
Closes #2604 
Added claudeAI chatbot details in database / ai tools / chat_bots.json
=> feat: added claudeAI chatbot link in ai tools / chat_bots

database/data_structures/dsa_courses.json, pnpm-lock.yaml
Closes #2620
Add algoexpert.io to Data Structures.json
=> feat: add algoexpert.io in Data Structures (#2620)

database/ai_tools/chat_bots.json
Closes #2629 
Added DeepSeek chatbot details in the AI Tools / Chat Bot / chat_bots.json
=> feat: add DeepSeek chatbot to AI tools database

database/data_structures/dsa_courses.json
Fixes #2637
Added the Strivers A2Z DSA Course/Sheet
=> chore: added TakeUForward in DSA

database/ai_tools/chat_bots.json
Example: Closes #2630 
added meta ai detail on AI Tools / Chat Bot / chat_bots.json
=> feat: added meta ai chatbot details in ai tools database

database/frontend/icons.json
closes #2634
add  SVGL as new icon resource
=> chore: add SVGL

database/design/design_inspiration.json
Closes #2641
Added link for fountn
=> feat: Add fountn link (#2641)

database/ai_tools/chat_bots.json
Example: Closes #2650 
added Grok ai details in chat_bots.json database file
=> feat: added Grok ai

database/ai_tools/chat_bots.json
Closes #2649 
Added ChatSutra AI details in ai_tools / chat_bots.json
=> feat: added ChatSutra AI chatbot details

database/frontend/themes_and_templates.json
Closes #2642
Add HTMLRev as a resource in category frontend, subcategory themes and templates
Also added a punctiation mark to ThemesBerg description for consistency
=> feat: Add link

database/ai_tools/chat_bots.json
Closes #2648 
added Qwen details in chat_bots.json
=> feat: added  Qwen chatbot details in chat_bots.json

database/other/devtools.json
Closes #2643
Adding Transform Tools
=> chore: [Add] Transform

database/frontend/ui_libraries.json
Closes #2656 
Add Magic UI to Frontend / UI Libraries
=> chore: add Magic UI library

database/frontend/ui_libraries.json
Closes #2665 
added react bits details in frontend / ui_libraries.json
=> chore: added react bits in frontend

database/frontend/ui_libraries.json
Closes #2667 
Add Headless UI details in frontend / ui_libraries.json
=> chore: added Headless UI into UI Library list

components/Footer/Footer.tsx
Closes #2671 
Add margin-bottom in footer tag
=> fix: margin bottom spacing on the footer

database/frontend/js_chart_libraries.json
Closes #2675 
added Mermaid as a JS Chart Libraries in frontend / js_chart_libraries.json
=> chore: add Mermaid Js to js_chart_libraries

database/frontend/ui_libraries.json
Closes #2676 
add FlyonUI UI library in frontend / ui_libraries.json
=> chore: add FlyonUI to UI Libraries

database/resources/project_ideas.json
Closes #2677 
add Made With React.js in resources / project_ideas.json
=> chore: add new project idea for Made With React.js

database/data.ts, database/index.ts, database/languages/php.json
Closes #2698 
added new subcategory in Language for PHP. Also added 2 resources for the PHP Programming Language.
=> chore: add php language

database/resources/project_ideas.json
Closes #2687 
add Made With Vue.js in resources / project_ideas.json
=> chore: added Made With Vue.js as a project idea

database/ai_tools/design.json
Closes #2688
Added Midjourney under AI Tools > Design category
=> feat(add): Added Midjourney under AI Tools > Design category

database/open_source/tools.json
Closes #2696 
added QuickRef.ME details in database / open_source / tools.json
=> chore: add QuickRef.ME

database/ai_tools/design.json
Closes #2689 
added stability ai details in ai_tools / design.json
=> chore: add stability ai

database/frontend/react.json
Closes #2704 
Add React Spinners to Frontend / React
=> chore: add React Spinners
