rupali-codes/LinksHub

components/SideNavbar/SideNavbar.tsx

#7
Created a hard-coded GitHub link and placed it with an icon below the sidebar navigation elements.
Please let me know if you would like this to be moved.
Is the plan to have a site config model where this data could be stored rather than hard coding the link ref?

[FEATURE] Add Github link to the site #7

---

components/SideNavbar/SideNavbarElement.tsx

Fixes https://github.com/rupali-codes/LinksHub/issues/56
Changes the sidebar elements to use <Link> instead of A to correctly follow coding guidelines and remove HTML warnings.

Change button to link for sidebar elements.

---

layouts/GeneralLayout.tsx

I fixed the classNames of GeneralLayout's div. In mobile view is the minium height `100vh - 80px`, because there is a `mt-20`. 
`m-20` is 80px. The minimum height is `min-height-screen` from `lg` breakpoint.
Closes #114

Fixed vertical overflow issue

---

components/Searchbar/Searchbar.tsx
components/Searchbar/index.ts
components/SideNavbar/SideNavbar.tsx
hooks/useSearch.ts
hooks/useSidebarSearch.ts

Created two search hooks:
-  useSearch: Manages search input and allows to use debounced search
-  useSidebarSearch: Uses previous hook to get data from database and filter it if needed 
Closes #114

Added search bar for sidebar.

---

components/Searchbar/Searchbar.tsx
components/SideNavbar/SideNavbar.tsx

Closes #172
The search bar is now fixed at the top of the page while scrolling, providing a better user experience for searching content on the site. This update ensures the search bar is always accessible and visible to the user, improving the overall functionality of the search feature.
- Desktop result:
https://user-images.githubusercontent.com/94737463/218251939-16974ffe-524f-42a5-92a5-8896ee8c7777.mp4
- Mobile result
https://user-images.githubusercontent.com/94737463/218251957-38f57736-b907-4249-a0d0-03c0cd71b9c2.mp4

Fix: SearchBar position to top while scrolling

---

components/BackToTop/BackToTopButton.tsx
components/Footer/Footer.tsx
components/Footer/index.ts
components/cards/index.tsx
layouts/GeneralLayout.tsx
pages/[subcategory].tsx
pages/index.tsx

Closes #117 
Suggest changes if any

added footer

---

components/Backdrop/Backdrop.tsx
components/SideNavbar/SideNavbar.tsx
components/popup/index.tsx
pages/_document.tsx

I added a reusable Backdrop component.
Closes #284
- Added reusable `Backdrop` component.
- Added a `div` to store the active backdrop in the `_document` file. The backdrop is just an overlay and is not a necessary part of the document flow in the `__next` div.
- Change the wrapper div's styles in the popup component. So the backdrops are consistent in both places.

feat: Added backdrop

---

components/Cards/CardsList.tsx

Closes #393 
This PR fixes the **Sort Link cards issue**
```diff
+ cards.sort((a: IData, b: IData) => {
+    if (a.name < b.name) return -1;
+    if (a.name > b.name) return 1;
+    return 0;
+ });
```

Sort link cards

---

database/frontend/animations.json

Closes: #417 
Add moving letters component to the animation section.
Card 'Moving letters' has been added.

Added Moving letters to animations

---

components/SideNavbar/SideNavbarCategoryList.tsx

- Add default text when search is empty
feature has been updated and tested its working perfect.
please verify the feature and let me know if there is any other modification required.
thank you

[Feature] Add default text when search is empty

---

components/popup/index.tsx

- Added extra space between the popup icons.
- I think the enclosing tag should be `div` instead of `h2`, so I made that change too.
Could you please check the PR to see if it fixes the issue? Thank you for the opportunity!

chore: [#485] Added Space Between Popup cons.

---

components/SideNavbar/SideNavbarCategory.tsx
components/SideNavbar/SideNavbarCategoryList.tsx

Closes #513 
- Now, the sidebar tabs behavior changed to "Only one tab open at a time".  
- Restructured the state management of open sidebar from individual component to the sidebarCategoryList component in order to close the other tabs.
- have handled the default open tab test case
[Working screen capture](https://www.awesomescreenshot.com/video/17489435?key=b39540671563a23d53ea81a82afb36e2)
I have restructured code in this way because I couldn't find any state management libs like redux. With redux, this could have been a bit easier and cleaner. But for now, according to me, this is the best approach without it. Still let me know if you have other ideas.

feat(frontend): #513 toggle sidebar menu

---

components/SkipLink/SkipLink.tsx
layouts/GeneralLayout.tsx

Closes #498 
Add a skip link component to the beginning of the layout, which is normally hidden but is the first thing in the tab order and becomes visible when a keyboard user focuses on it. Activating the link jumps to the main content and allows the user to skip over tabbing through all of the navigation links.
My computer is misbehaving and won't let me take a screenshot right now. But to see the link just navigate to the site and start tabbing. It will appear as the first thing in the tab order in the top center of the page.

Feat: add skiplink

---

CONTRIBUTING.md

Closes #590 
I added a special note for GSSoC'23 contributors in the Issues section. 
Hey, @rupali-codes! :) I decided to create this special note to make it easier for us to determine if contributors are participating in GSSoC'23. Let me know what you think. :)

[fix] add a special note for GSSoC'23 contributors

---

database/youtube/data-structures.json

Fixes #565 
Adding direct links of  data strucure and algorithm playlist instead of their channel links. 
@CBID2

Adding direct links to dsa playlists

---

.github/workflows/close_old_issues.yaml

I have created a workflow for closing old issues. Please note that this action uses the personal access token for authorization so a `GITHUB_TOKEN` has to be added to the repository's secret

Added github action for closing old issues

---

components/Cards/Card.tsx
components/Cards/CardsListItem.tsx

closes #671 
fixes #671 
Read more button is added for the card when the text over flow

Read more button added when text overflow on card

---

database/frontend/ui-generators.json

chore: Add one link(https://fffuel.co/) for UI generation. fffuel is a collection of color tools and free SVG generators for gradients, patterns, textures, shapes & backgrounds.
Closes #758

chore: Added one link for ui generation

---

components/Cards/Card.tsx
components/Footer/Footer.tsx
components/SocialMedia/SocialMediaIconsList.tsx

- Closes: #842 
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from security vulnerabilities and improve performance. It is a good practice to use this attribute on all external links.
- Overall this …

💡 [Feat]: Add aria-label for Social anchors & Some minor changes

---

components/Cards/Card.tsx

Closes #732 
- I have fixed the responsive bug.
|  Before | Updated |
|:--------:|:----------:|
| ![before](https://user-images.githubusercontent.com/74038190/240995120-29613209-4953-4f5e-b49c-37aa29154767.png) | ![after](https://github.com/rupali-codes/LinksHub/assets/74038190/9e67444a-b9b2-4616-9a2d-8a6172fee73b) |
- I have properly tested, and I believe this is the sole reason for the bug.
- I have checked; other contents are not impacted.
- I have verified this by increasing the header text and adding other custom values.

fix: overflowing content bug

---

CONTRIBUTING.md

Fixes #798 
I added a link to GitHub’s documentation on solving merge conflicts. 
Let me know if I placed the link in the proper spot.

[fix] add article on how to solve merge conflicts

---

components/ForkButton/GitHubForkButton.tsx
components/SocialMedia/SocialMediaIconsList.tsx

Closes #774 
- Add the button using https://github.com/buttons/github-buttons as discussed in the issue
> Dark Mode Lg
> Light Mode Lg
It doesn't support custom `CSS` code, and I tried applying it to the parent container, as that is the only way it works. So, this is the best we can do.
> Dark Mode Sm
I believe it is unnecessary to display the fork button on small-screen devices as it may not place well with the social media icons.
As I mentioned earlier, please ensure that the same is done for maintaining a clean history.

feat: add github fork button

---

.github/workflows/author-assign-pr.yml

Resolves #978 
- Reference: https://github.com/toshimaru/auto-author-assign
- The purpose of this workflow is to automatically assign the author of the pull request. It uses the provided `GitHub token`  
(`secrets.GITHUB_TOKEN`) to perform this action.
- By using this workflow, the author of a pull request will be automatically assigned when the pull request is opened or reopened in the repository.
```yml
name: 'Author Assign'
on:
pull_request_target:
types: [opened, reopened]
permissions:
pull-requests: write
jobs:
assign-author:
runs-on: ubuntu-latest
steps:
- uses: toshimaru/auto-author-assign@v1.6.2
with:
repo-token: '${{ secrets.GITHUB_TOKEN }}' # GITHUB_TOKEN will be used by default
```

docs: add workflow to assign pr to the author

---

.github/workflows/lock-issue.yml

Resolved #966 
- Reference: https://github.com/dessant/repo-lockdown
```yml
name: 'Issue Lockdown'
on:
issues:
types: opened
permissions:
issues: write
jobs:
action:
runs-on: ubuntu-latest
steps:
- uses: dessant/repo-lockdown@v3 # Reference: https://github.com/dessant/repo-lockdown
with:
close-issue: false
process-only: 'issues'
issue-labels: '🔒 locked'
exclude-issue-labels: '🚀 ready'
skip-closed-issue-comment: true
issue-comment: >
To reduce notifications, issues are locked. Your issue will be unlocked when we will add label as `🚀 ready`.
```
- The bot will add the `🔒 locked` label before locking the conversation, and you can unlock the conversation by adding the `🚀 ready` label.
- If you prefer a different label, please let me know, and I will update it accordingly.
@rupali-codes …

docs: add workflow to lock issue conversations

---

components/Searchbar/Searchbar.tsx

This PR closes issue #1042
I made changes in Searchbar Components 
when the input is empty search string will also be empty 
https://github.com/rupali-codes/LinksHub/assets/65841021/4062c704-1738-4b9b-b19c-543968926509
So there is one new issue that when the searched categories are open and if we go back to menu the starting categories are open

Fix issue #1042 Categories not showing when the search is empty

---

database/resources/official-docs.json

Next.js Documentation are Added in Official Docs in Resources
Closes  #1141
Offical Documentation for Django is added under Offical Docs Section

 Next.js Documentation are Added Under Official Docs

---

database/frontend/online-code-editors.json

Closes #1118
Closes #1118 
Add a new online code editor for html, js, css with compiler for 60+ programming languages and frontend frameworks.
Should I commit changes after running it locally?

add the new link for OneCompiler

---

database/resources/official-docs.json

Closes #1203
[Attach screenshots here if applicable]
Thank you for reviewing this pull request!

Add nuxt Documentation to Official Docs in Resources 📃

---

database/frontend/fonts.json

Closes #1204 
I added DaFont to the fonts subcategory of the frontend category.

chore: Add DaFont to frontend/font category

---

hooks/useSidebarSearch.ts

Resolves #1205 
I don't think this is an issue anymore because once we apply it to the queue, the problem arises at line
```typescript
setSearchResults(results) // this is a problem
```
I attempted to refactor it and separate it to improve understandability. You can review the PR and let me know if the refactored code meets the requirements. If it doesn't meet the expectations, I suggest closing it accordingly.

refactor: useSidebarSearch component

---

components/SideNavbar/SideNavbarBody.tsx

Closes #1309 
> Fixed warning
I was confused because the CSS classes `transition-all` and `transition-none` are used together in the same line. I need clarification on whether you want to keep both classes or remove one of them. Please let me know your preference so that I can make the change.
```css
transition-all transition-none
```

fix: warning due to any non-nullish value

---

database/backend/authentication.json

Issue #1333 
closes #1333
Add the Passport authentication middleware in the backend authentication category
Please merge this pr with gssoc23 labels

Add Passportjs

---

data/maintainersData.ts
pages/contributors.tsx
styles/globals.css

Closes #1300
> I created a new issue, because I believe we need to implement one more section just for maintainers.
Same for maintainers, showing `M` and for Contributors showing `C`
I implemented the hover part, because tool tip would not be great for custom styling.
> Hover
> Normal
@rupali-codes 
This should be a level 3 PR since it was very tough to implement and it's a new feature.

feat: show maintainers/contributors state in contributors section

---

components/SocialMedia/SocialMediaIconsList.tsx
tailwind.config.js

Close #1299 
- Revamped the hover states of all icons to the site's primary violet color `#8B5CF6`
- Removed the unnecessary color codes after revamping the hover states so that we could clean the old ones.
https://github.com/rupali-codes/LinksHub/assets/92252895/bb823f7f-64ef-482c-9aab-f5e38be6e5bd

revamp: hover states of social icons ✨

---

database/frontend/react.json

Add DevHints.io React.js cheatsheet to the Frontend/React category.

---

components/Backdrop/Backdrop.tsx
components/SideNavbar/SideNavbar.tsx

Closes #1007
Used existing react-transition-state library with useTransition hook.

Feat: Sync overlay transition with sidebar transition in mobile view

---

database/machine_learning/data-science.json

Closes #1273
Kaggle is a data science competition platform and online community of data scientists and machine learning practitioners under Google.

Adding Kaggle site.

---

database/data.ts

Closes #1287
I raised an issue to add a new link, but it turned out that there was already a link for that. The problem was in the `data.ts` file, where they mentioned `dsa` in the URL instead of `data-structures`, causing it to redirect to `dsa`. I simply replaced `dsa` with `data-structures`, and now it works perfectly for me.
**My question:** Is it okay to make this change only in the `data.ts` file, or should I update the subcategory for all the links present in `data-structures.json"?

Bug fix in Data Structures 

---

CONTRIBUTING.md

Closes #1419 
- This clearly states that contributors should add a description to merge the pull request into the codebase. Therefore, whenever someone is adding a new subcategory, make sure to refer them to the contributing guidelines and ask them to include a description.
> Image

docs: update contributing guidelines while adding subcategory

---

pages/_document.tsx

Closes #1408 
1. Fixes
2. With `strategy="lazyOnload"`, the Script component will be loaded lazily when the page has finished loading. This can help improve the page's initial loading time by deferring the loading of non-critical scripts until after the page has been displayed.
Reference: https://nextjs.org/docs/pages/building-your-application/optimizing/scripts
3. Using `Script` component from Next.js

feat: optimize script for google analytics with lazy loading and Script component

---

.github/labeler-config.yml
.github/workflows/add-labels-pr.yml

@rupali-codes 
Reference: https://github.com/hoho4190/issue-pr-labeler
Closes #1056 
You can test it here: https://regex101.com/
I am taking two examples, which you must read so that you can properly review the PR.
- `/\bfeat\b/`: This regular expression matches the exact word "feat" with word boundaries (`\b`). It will match strings that contain the word "feat" as a whole word, but not if it's part of another word (e.g., "defeat" or "feature").
- `/feature/i`: This regular expression matches the word "feature" (case-insensitive) anywhere within a string. It will match strings that contain "feature" in any combination of uppercase and lowercase letters (e.g., "Feature", "FEATURE", "feature").
1. This is the only label `goal: build` that I have used since there was none. So, you can create …

feat: workflow to add labels based on title and comment

---

components/ForkButton/GitHubForkButton.tsx
components/StarButton/GitHubStarButton.tsx

Closes #1410 
@rupali-codes 
There was redundant code in the Tailwind styling, so even if you don't need the border, you can definitely merge this.
> duplicate code
If you want a border, let me know so that I can make the change with `GitHubStarButton`. If you don't want a border, then I will remove the extra code.
Please let me know your decision.

feat: remove redundant code and add styling

---

database/frontend/react.json

Closes #1374 
Added resources for react

Add react resources

---

components/Searchbar/Searchbar.tsx

Close #1407 
- Added proper ` <label>` element which has a `"for"` attribute that corresponds to the `"id"` attribute of the `<input>` element. This association is what makes the label functionally related to the input field.
-  When the user interacts with the label or its associated input, the browser handles the connection, ensuring proper focus and accessibility behavior.
- By doing so, it helps users, including those with disabilities, better understand the purpose of the form control and interact with it more easily. The usage of `<label>` is crucial for all aspects of accessibility.
- Additionally we make the `<label>` hidden by adding `sr-only` class, So that it couldn't visible to the user visually but it can be visible to the accessibility device user. We can ensure our search …

feat: made search bar accessible 🔍✨

---

styles/globals.css

Close #1478 
- I'm excited to propose a pull request that enhances the accessibility of our Linkshub repository. In this PR, I've introduced reduced motion styles to accommodate users who have enabled the "prefers-reduced-motion" setting in their devices or browsers.
- To improve the user experience for motion-sensitive users, I've implemented a media query in `global.css` to target devices with reduced motion preferences. The following enhancements have been made:
- **Minimized Animations**: By targetting`animation` property for all elements, pseudo-elements (::before, ::after), and transitions, we effectively cancel any animations on the page.
- **Reduced Transitions**: By targetting `transition` property, all transitions are disabled, ensuring that elements don't animate when their …

feat: implement prefers reduced motion feature to enhance accessibility 🚀✨ 

---

database/youtube/web-development.json

added Wes Bos youtube in webdevlepment section

---

components/SideNavbar/SideNavbarBody.tsx
styles/globals.css

Closes #1418 
> Why search bar should be sticky.
- Users can keep their search query visible while exploring different categories. This helps them remember their search context and makes it easy to refine or modify their search without losing sight of the results.
- With a sticky search bar, users can focus on interacting with the search input without distractions, as it remains in a fixed position regardless of their scrolling behavior.
> Sticky search bar
- I initially attempted different styling approaches but later changed my approach after trying various options, as this one appeared to be the most sophisticated and easy to understand.

feat: make search bar sticky and adjust scrollable area

---

.github/workflows/spellcheck.yml
data/maintainersData.ts

Closes #1080 
The GitHub Action will now automatically run codespell on your JSON files every time you push to the main branch or open a new pull request. If it detects any spelling errors, the Action will fail, indicating that you need to fix the identified issues.

Spellcheck

---

database/resources/official-docs.json

Closes #1523 and unblocks #1398

Fix Express.js url

---

database/youtube/data-structures.json

Closes #1375
Add dsa resources in javascript

dsa resources

---

components/Header/Header.tsx
components/ThemeToggler/themeToggler.tsx
package.json
pages/[subcategory]/index.tsx
pages/index.tsx
pages/search.tsx
pnpm-lock.yaml

Close #1506 
- In this pull request, we've added an exciting enhancement to the LinksHub user experience. Recognizing the significance of immersive user interactions, especially within the context of Progressive Web Apps (PWAs), we've integrated a dynamic browser bar theme feature.
1. **Dynamic Browser Bar Color:** Depending on the selected theme (dark or light), the browser's address bar will adapt its color accordingly, providing a seamless visual transition and consistency.
2. **PWA Compatibility:** This feature is fully compatible with the PWA version of LinksHub, ensuring that users who've installed LinksHub on their devices get a consistent and immersive experience.
- **Enhanced User Experience:** The adaptation of the browser bar color according to the app theme offers users a …

feat: implement adaptive day/night browser bar theme 🚀🔥 

---

CONTRIBUTING.md

Closes #1573 
I reorganized the Commit sections in the Contributing file

fix: revise commit section in contributing guide

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Closes #1601 
New automation has been added for drafting a release, on pushes/PR merges to the `main` branch and based on a custom template `.github\release-drafter.yml`, release notes will be generated automatically and the versions will be bumped accordingly.

feat: added automation for drafting a release

---

hooks/useFilterDB.ts

Closes #1616 
Used `===` for exact match

fix: exact match for subcategory

---

layouts/GeneralLayout.tsx

@Anmol-Baranwal 
When the sidebar is open in mobile view, the main content behind the sidebar should remain fixed and not scroll.

feat: make screen non-scrollable in mobile view when sidebar is open

---

components/Header/Header.tsx
layouts/GeneralLayout.tsx
package.json
pnpm-lock.yaml

Closes (#1422)
I added a border to the bottom of the `Header.tsx` file for the visual distinction between top bar and cards if the route is anything other than "/".  I used the next/navigation `usePathname` to identify what the current path is.
I added the **clsx** dependency via _pnpm_ which allows for conditional statements within the className without having to use template literals.
```javascript
<header
className={clsx(
'fixed top-0 left-0 z-30 row-start-1 row-end-2 flex h-[76px] w-screen items-center justify-between bg-light-primary dark:bg-dark border-b border-b-light-primary dark:border-b-dark-primary',
pathname != '/' &&
'lg:border-b lg:border-b-theme-primary lg:dark:border-b-theme-secondary transition-color ease-in-out duration-150'
)}
>
```

Top bar distinction feature

---

components/BackToTop/BackToTopButton.tsx

Closes #1656 
The back to the top button must only be hoverable at the top else it should be hidden and not hoverable.
[screen-capture (1).webm](https://github.com/rupali-codes/LinksHub/assets/93988200/48677fde-5e3f-4a33-b4ff-69ab67bbe326)
The hidden property will only be added once the use scrolls past SCROLL_LIMIT.

fix: Back to top button hoverable even at the top

---

components/SocialMedia/SocialMediaIconsList.tsx

Closes #1464 
This PR adds ordered lists (`<ol>`) around the GitHub buttons and social media icons in the `SocialMediaIconsList` component, making the code more accessible for screen readers.
Hey @Anmol-Baranwal. I've never really worked with Typescript before, so feel free to make the necessary adjustments.

fix: improve accessibility of scripts

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/index.ts
database/technical-writing/tools.json
types/index.ts

Closes #1693 
Closes #1692 
I added a technical writing category with a "tools" subcategory with a link to Docsify 
It's still a WIP

add: techncial writing category and Docsify 

---

.github/workflows/spam_hacktoberfest.yml

> Reference: https://github.com/maximelafarie/spamtoberfest
> Can't find any other workflows.
Closes #1702 
- I don't really how the workflow works, except that it will close the PR.
- Also, I don't think closing would be the right option, contributors can get a chance of correcting their mistakes.
> Current option is `flag`, let me know if you want me to change it to `default`.
- There are two options as listed in the workflow:
- `flag` - only adds a "Spam" label to the PR
- `close` - adds a "Spam" label to the PR and closes it
- What does this means?

chore: add workflow to check spam PRs in hacktoberfest

---

components/Searchbar/Searchbar.tsx
components/Searchbar/SearchbarSuggestions.tsx
types/index.ts

All subcategory are now displayed in the search bar suggestions. Also, we don't need to keep two lists of subcategories in different places anymore.
Closes #1746 
https://github.com/rupali-codes/LinksHub/assets/70102539/9840c747-5b05-4063-917c-b43533dae88c
I had a hard time deciding if I should open this PR. While the commit message doesn't relate to the issue, I found out this is the solution while working on the issue. If you check the subcategories we have, you'll notice that some subcategories have `&` like `Themes & Template` while some have `/` like `CI/CD`. We even have `C#`😅.
So to avoid having a series of `if` statements while providing:
- complete suggestions
- correct URL
I thought it's better we derive the suggestions from the actual …

feat: Improve search bar suggestions

---

components/Searchbar/Searchbar.tsx

Closes Issue #1518 
When searchbar is cleared it go back to the home page if  the url contain a query tag or it will remain on the same page if a query tag isn't present
https://github.com/rupali-codes/LinksHub/assets/65841021/6c58e7ea-fce5-4d0b-9617-281400662d11

Fix searchbar query persist even after clearing the searchbar

---

.github/ISSUE_TEMPLATE/---category-suggestion.yml
.github/ISSUE_TEMPLATE/add_link.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/category_description.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/ISSUE_TEMPLATE/refactor_code.yml

Resolves #1744 
- Add this option in all issue forms (except `Other`)
- Remove additional context from documentation issue form
The issue form is very long, and to make it very concise like other issue forms in the repo. It is better to remove extra sections.
@CBID2 @rupali-codes 
Review this.

chore: add option to check participation in hacktoberfest

---

components/Footer/Footer.tsx

##Fixes Issue 
closes #1736 
- Removed class `py-2` from footer which was causing the issue.
##Note to reviewers
Please check it @Anmol-Baranwal @rupali-codes

Fix - remove slight scroll behavior from categories page

---

components/TopBar/TopBar.tsx

Closes #1725 
the data-tooltip-id , data-tooltip-content, data-tooltip-place were shifted to the children Icon

chore: correct the layout of description icon of subcategories for hover state

---

CONTRIBUTING.md
README.md

Closes #1732 
- `Readme.md` with menu link
> Image
- `Contributing.md`
> Image
@rupali-codes  @CBID2 
- Let me know if any changes are required.
- Feel free to suggest if something doesn't feel right.

chore: add maintainers info with usernames

---

database/competitive_programming/cp-tutorials.json

#1843 
closes #1843
I have changed the sources in competitive programming tutorial page. In database->competitive-programming->cp-tutorials

cp tutorial page fix

---

database/backend/email-providers.json
database/data.ts
database/index.ts

closes #1860
a) Added "Email Providers" as a new subcategory in the backend section.
b) Included links to popular email service providers like Nodemailer and SendGrid within the "Email Providers" subcategory.
c) Updated the navigation menu to include a link to the new "Email Providers" subcategory.
d) Ensured that the subcategory is organized and styled consistently with the rest of the website.
e) Tested the functionality of the new subcategory to ensure smooth user experience.

added emailProviders as subcategory in backend

---

.github/ISSUE_TEMPLATE/---category-suggestion.yml
.github/ISSUE_TEMPLATE/add_link.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/category_description.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/refactor_code.yml
.github/labeler-config.yml
.github/workflows/greetings.yml
pages/contributors.tsx

Closes #1730 
Closes #1727 
- Already mentioned in the Issue description
@rupali-codes @CBID2 
I need to implement these,
> Can you suggest something.
I found this workflow out of several others: https://github.com/nearform-actions/github-action-check-linked-issues, but I don't understand what it does after finding the linked issues count.
So, maybe we have to sync three workflows, one to find linked issues, then close a pr and then add a comment on the PR.

feat: add mandatory changes

---

package.json
pages/index.tsx
pnpm-lock.yaml

Closes #1735 
Added Link to wrap over the Typewriter component to redirect to the particular section page when click on the text
Removed autostart and loop as it causes the text to repeat twice

feat: redirect to the corresponding section based on options in empty page screen

---

database/frontend/illustrations.json
database/frontend/themes-templates.json

Closes #1879
a) Added links to FreeFrontend  "Themes and Templates" and  subcategory of the frontend.
b) Added links to IconScout  "Illustration" and  subcategory of the frontend.
b) Updated the subcategory's content to include brief descriptions of FreeFrontend and Illustration.
c) Ensured that the new links are well-formatted and functional.
d) Organized the subcategory to maintain consistency with existing resources.
e) Verified that the links accurately direct users to the relevant Postman and Cypress resources.

adding FreeFrontend and IconScout to themes and illustration respectively

---

.github/CODEOWNERS

Closes #1805 
One of the maintainers does not have write access to the repository, so this PR replaces their name with a maintainer that does have write access.  
N/A

fix: revise errors in CODEOWNERS file

---

database/youtube/machine-learning.json

Closes #1813 
- Add the Youtube link for YannicKilcher channel and description in the machine learning category.

Adding Yannickilcher channel in machine learning category

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/frontend/ui-libraries.json
database/index.ts

Closes #1927 
added a sub category in Frontend section  named UI Libraries.

UI libraries in fronted added

---

components/SideNavbar/SideNavbarCategory.tsx
pages/[category]/index.tsx

Closes #1978 
- Changed `aria-label` attributes of category links for better screen reader accessibility.
- Added `aria-label` attributes of subcategory links for better screen reader accessibility.

Add Accessibility Improvements to Links

---

database/backend/api.json

Closes #2048 
This PR adds NASA's API to the `API.json` file.

Added NASA's API in  api.json

---

components/BackToTop/BackToTopButton.tsx
components/Footer/Footer.tsx
layouts/GeneralLayout.tsx
pages/[category]/[...subcategory].tsx
pages/[category]/index.tsx
pages/index.tsx
pages/search.tsx

Closes #2051 
- Removed unwanted margin from Footer component
- Optimized Back to Top button position for Mobile devices
- Minor changes for other components too, because when updating Footer it affected other components too.
|BEFORE - [ MOBILE ] |AFTER - [ MOBILE ]|
|:---:|:---:|
|![BEFORE - [ MOBILE ]](https://github.com/rupali-codes/LinksHub/assets/92252895/c480f6e5-90e9-4743-8e9b-c8b1bbbfa6d9)|![AFTER - [ MOBILE ]](https://github.com/rupali-codes/LinksHub/assets/92252895/44d13b8f-97ab-4e50-bfff-8a6e86b2f2d1) |
|BEFORE - [ DESKTOP ] |AFTER - [ DESKTOP ]|
|:---:|:---:|
|![BEFORE - [ DESKTOP ]](https://github.com/rupali-codes/LinksHub/assets/92252895/74e0577c-047c-48fa-ad5a-a9ab521c2eb2)|![AFTER - [ DESKTOP ]](https://github.com/rupali-codes/LinksHub/assets/92252895/04ef3417-44c6-4b16-a39 …

fix: footer layout issue ⚒️✨ 

---

components/Cards/Card.tsx
components/popup/popupInfo.tsx

This PR closes issue #1926 
Closes #1982
Added small icons next to the "Visit Site" button to signify the destination type:
- Display a YouTube logo icon if the link redirects to YouTube (for users who prefer video tutorials).
- Show a "document" icon if the link redirects to an article, blog, or documentation website (for users who prefer reading). 
- `components/Cards/Card.tsx`
[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/743a10cd-8135-48e8-b11b-814a2a28075d)
@rupali-codes , @Anmol-Baranwal , @CBID2 please review this PR.
Thanks

feat: add icons next to the "Visit Site" button to signify the destination type

---

database/backend/email-providers.json

Closes ##2110
This commit introduces a new link to Novu.co at "backend/email-providers"
Novu is an open-source notification infrastructure that allows developers to send notifications to their users through multiple channels.

feat(add link):  Add a new link to Novu in the backend as an email provider

---

database/frontend/fonts.json

Closes #2113 
This commit introduces a new link to Fontspace.com at "frontend/fonts"
FontSpace is a font directory with more than 100,000 available fonts. It takes a visual approach to displaying fonts. Along with the usual editable font preview, you'll also find an image from the designer that showcases the font.

feat(add link): Add a new link to Fontspace in the frontend as a fonts provider

---

components/Searchbar/Searchbar.tsx
database/data.ts

Closes #2139 
Fixed showing resources without sidebar subcategories getting displayed & Capitalization of each word in the search query.

Fix-#2139/Searchbar-react-bug

---

.github/CODEOWNERS

Closes #2166 
This PR adds Aftab to the codeowners file

feat: adding Aftab to Codeowners file

---

.github/workflows/handle-multiple-issues.yml

> docs: https://github.com/Anmol-Baranwal/handle-multiple-issues
resolves #1844 
- This will save us the trouble from checking if contributors have created issues or not.
This is what this workflow will do.
- It will find the issues that is created by the author and is in `open` state.
- It will add a label of `multiple issues` if there are any
- It will be ignored for us as collaborators and maintainers
- It will comment a message.
```
The message will be:
```
@rupali-codes @CBID2 @aftabrehan 
You can see the workflow, and suggest the changes.
- We can also filter if any issues are assigned to the author.
- We can multiple labels if we want.

chore: add workflow to handle multiple issues

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/index.ts
database/other/text-formatting.json

Added a card in Text Formatting - Text Tune

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/devops/iac.json
database/index.ts

Closes #2203
- New sub-category under devops category called `IaC`
- Two `Terraform` content under IaC sub-category
- Official documentation
- Youtube course for beginners
If you have any comments, please let me know and I'll correct them as soon as possible.

feat: add 'IaC' sub-category with 'Terraform' content under 'devops' category

---

CONTRIBUTING.md
README.md

Closes #2205 
This PR addresses the following issues:
1. Adds Aftan to the Maintainer's section in the README file
2. Adds a code snippet in the section of Contributing guide that describes the steps to adding categories/subcategories.

docs: updating the README and Contributing Guide

---

components/Aside/Aside.tsx
components/MobileBottomNav/MobileBottomNav.tsx
components/Searchbar/ShortcutKey.tsx
components/SideNavbar/SideNavbar.tsx
components/SideNavbar/SideNavbarBody.tsx
components/SideNavbar/SideNavbarCategoryList.tsx
styles/globals.css

Closes #2202
- added the new design for the searchbar

feat: add searchbar for mobile devices (new design)

---

components/Pagination/Pagination.tsx
pages/[category]/[...subcategory].tsx

#2071-Side pagination

---

components/Pagination/Pagination.tsx
pages/[category]/[...subcategory].tsx

Closes #2238 
- Added a numberOfCards variable to [...subcategory.tsx] to track the number of cards on each page.
- Used numberOfCards within Pagination.tsx to calculate if there are 3 or less cards in a page.
- Added a div that adds padding above the pagination element if there are 3 or less cards on the page.
I am very new to this so please criticize.

BUG] Align pagination buttons to bottom

---

README.md

Improved the Support Section #2242
README.md support section was updated.
Before
After
Can I be a cotributor ?

[docs] Improve the Support Section

---

layouts/GeneralLayout.tsx

close #2262
Remove extra spaces between Breadcrumb and Content

#2262: fix extra space in between Breadcrumb and Content

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/frontend/3d-libraries.json
database/frontend/three.json
database/index.ts

Closes #2270 : Change threeJS subcategory name to 3d libraries and add resource links
- Change the subCategory called **threeJS** under the frontend _category_ to **3D Libraries**
- Modify the `CategoryDescriptions.ts` file to include 3D Libraries.
- Rename file called `three.json` in the frontend database folder to include all the URLs related to 3D Libraries.
- Modify the `index.ts` file in the database folder to include 3D Libraries.
- Modify the `data.ts` file in the database folder to include 3D Libraries.

Change threeJS subcategory name to 3d libraries and add resource links

---

components/Pagination/Pagination.tsx

This pr closes #2302 
added findClosestScrollElement function inside useEffect on first render of pagination
that function will find closest scrolling element and use it for scrolling when user changes page
Use that behavior in order to prevent bugs in future when pagination could be implemented in any part of a project Or the main scrolling element will be changed
that fix prevents almost all future scrolling bugs here  
Small screencast to demonstrate how it works now
[Screencast from 03-17-2024 12:34:25 PM.webm](https://github.com/rupali-codes/LinksHub/assets/78084319/bed0008c-03dc-44f6-a1df-f5343deb88a8)
Thank you for opportunity to contribute to your project!
I open for any discussion feel free to ask any questions and leave comments)

Closes #2302

---

database/frontend/js-chart-libraries.json

fixes #2289
Add new JavaScript charting libraries 
In the interest of providing additional context, I've included some further resources.
Additional resources:
- [Vega](https://vega.github.io/vega/) is a visualization grammar, a declarative format for creating, saving, and sharing interactive visualization designs.
- [Victory](https://formidable.com/open-source/victory/) is a React.js components for modular charting and data visualization.
- [C3js](https://c3js.org/) is a D3-based reusable chart library.

Add new JavaScript charting libraries

---

database/cybersecurity/defensive_security.json

#2331 
changing two links that have weong pages or the page was not found

Links fixed

---

database/data.ts
database/devops/automation-tools.json
database/index.ts

closes #2345 
Adding a sub category named Automation Tools where, insert various tools in this category.
---
---
- **Ansible Automation**- [view](https://www.ansible.com/)
- **Terraform Infrastructure**- [View](https://www.terraform.io/)
- **GitLab CI/CD**- [View](https://docs.gitlab.com/ee/ci/)
- **Configuration Management with Puppet and Chef**- [View](https://www.puppet.com/)
> @Anmol-Baranwal Anmol, is this correct, or should I post a link to another website? Please let me know if there are any issues with the tools.

feat: [ADD]-Sub Category- Automation Tools #2345

---

database/backend/api.json

It adds a new link to 'Free APIs' in the `backend/api` section in the website.

added FreeAPIs link to backend/api

---

database/backend/validation.json
database/frontend/angular.json
database/frontend/next.json
database/languages/c-programming.json
database/languages/csharp.json
database/resources/hosting.json

Add new resources in different categories

Add new resources

---

.github/workflows/check_links.yml
.lycheeignore

* Check links #2357
Closes #2357
https://github.com/JuanPabloDiaz/LinksHub/issues/39

Broken Link Checker - Github Action

---

components/SideNavbar/SideNavbarCategory.tsx

#2430 
This pull request addresses an issue where certain category names were not being capitalized correctly. Specifically, categories such as "ai-tools" were displayed as "Ai Tools" instead of "AI Tools"
Changes: 
Added categoriesToUppercase array to specify words that need to be fully capitalized.
Implemented the capitalizeCategory function to handle capitalization logic.
Updated the SideNavbarCategory component to use the capitalizeCategory function for displaying category names.
Closes #2430

fixes typo in sidebar

---

pages/[category]/index.tsx

Closes #2449 
Rename `"descrition"` to `"description"`

chore(refactor): typo in category page

---

package.json

Closes #2436 
renames the package name to "linkshub"

chore: rename package name

---

components/Header/Header.tsx

Closes #2439 
Removes redundant React Fragment: `<></>` from the `renderLinks()` function in `components/Header/Header.tsx`

fix: key prop bug

---

components/Header/Header.tsx

Closes #2438 
1. Rename "Our Team" to "Team", as the word "our" also includes the reader (which may or may not be the part of the team).

chore(typo): rename our team button

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/index.ts
database/tech_articles/react.json
types/index.ts

Closes #2472 
Adds a new category: Tech Articles
Subcategory: React with 5 links

chore: add tech articles

---

database/youtube/web_development.json

Closes #2471
Fixes a youtube broken link in youtube/web_dev
The report generated by github actions in #2471 has only one broken link.
Other links in the error reports works fine

fix: broken link

---

database/other/podcasts.json

Closes #2479
- Added "Virtual Coffee" podcast link to `other/podcasts` category.
Please review the added link and ensure it follows the project's contribution guidelines.

chore: Add Virtual Coffee podcast link (#2479)

---

database/open_source/projects.json
package.json
pnpm-lock.yaml

Closes #2502 
-Added  Abbreve open source project link to open_source/projects.json.
-Abbreve is an open-source dictionary for slang. With Abbreve, you'll never have to feel left out of a conversation or unsure of the meaning of an abbreviation again.
- No major changes to functionality, only data addition.

feat: add Abbreve project link to open_source/projects.json

---

database/backend/api.json

Closes #2497
Added the JSONing API in the backend category and api subcategory
Kindly review the PR.

chore: new link jsoning api

---

database/data.ts
database/design/design_color_tools.json
database/design/design_tools.json
database/index.ts

Closes #2501 
Moves `Frontend > Colors` to renamed `Design > Design Color Tools`

feat: moves `frontend > colors` to renamed `design > design color tools`

---

database/other/devtools.json

- A new source of dev tools, HackMD, is added, and recommended. It is not only user-friendly in UI perspective, but also convenient for developers to organize notes etc.

feat: Add a New Card in DevTools category

---

.github/workflows/auto-assign-issues.yml
CONTRIBUTING.md

[Feature] Create GitHub workflow to assign issues to users on comment 'take' 
fixes #2507

feat: add github action to self-assign the issue

---

pages/index.tsx

chore: Update 'Contribute now' button link

---

pages/index.tsx

This PR is relevant with addressing Issue #2537. 
Suggest updating the width size of both columns in LinksHub intro. 
After testing in the 4 different screen sizes, including small, medium, large, x-large, of devices, the modified width could avoid text overflown. 
The columns also looked aligned after updated.

chore: fixed text overflown in LinksHub intro columns

---

database/languages/css.json

Fixes #2546 
Adds the following to the css.json file in "database/languages/"  folder
`"name":"CSS-Tricks",
"description":"CSS-Tricks is a leading web development resource offering tutorials and articles focused on CSS, as well as other front-end topics like HTML, JavaScript, and design. Known for its practical solutions and community-driven forum, it's a go-to site for developers of all levels.",
"url":"https://css-tricks.com/",
"category":"languages",
"subcategory":"css",
"language":"English"`
None

chore: added new resource for the css sub-category

---

components/TopBar/CategoryDescriptions.ts
database/CMS_toolkit/headless_cms.json
database/CMS_toolkit/traditional_cms.json
database/data.ts
database/index.ts
types/index.ts

Closes #2560 
- Add `CMS Toolkit` category.
- Add `Traditional CMS` subcategory.
- Add `Headless CMS` subcategory.

feat(category): add 'cms toolkit' close #2560

---

database/other/devtools.json

Closes #2547 
adds the following to databse/other/devtools.json
{
"name": "Can I Use",
"description": "Can I use is a valuable web tool that helps developers check browser support for various web technologies, including CSS, HTML5, JavaScript, and APIs. It provides up-to-date compatibility data for different browsers and versions, helping developers ensure cross-browser functionality in their projects.",
"url": "https://caniuse.com/",
"category": "other",
"subcategory": "devtools"
}
merging this branch, adds the webpage can i use in the devtools category

feat: added can i use to database/others/devtools

---

database/technical-writing/tools.json

Closes #2574
append new object for link in database/technical-writing/tools.json

feat: add overleaf as a new link under <Technical Writing/Technical Writing Tool>

---

components/TopBar/CategoryDescriptions.ts
database/backend/nest_js.json
database/data.ts
database/index.ts
pages/[category]/[...subcategory].tsx

I have added new subcategory in the backend category. that is Nest - A progressive Node.js framework for building efficient, reliable and scalable server-side applications.
Fixes #2588

feat: Added Nest.js course in Backend category

---

database/data.ts

Closes #2590 
Updated search suggestion object data name "react" with "react articles" in the database / data.ts

fix: Change search suggestion name 'react' to 'react articles' (#2590)

---

pages/contributors.tsx

Closes https://github.com/rupali-codes/LinksHub/issues/2609
- fixing paddings and margins in contributor grid item
- icons are falling out of the box
- this is my first PR to this beautiful repo
- I hope to contribute more and learn from the best <3

fix: improve responsiveness in grid

---

components/TopBar/CategoryDescriptions.ts

Closes #2603 
The VueJs description was added to CategoryDescriptions.ts by modifying the categoryDescriptions object with a new vue_js key-value pair in the frontend section.

feat: added VueJs desc in CategoryDescriptions.ts

---

components/SideNavbar/SideNavbarCategoryList.tsx
database/data_structures/dsa_articles.json

Description:
Added a link to Algomap.io under the DSA Articles section in the Data Structures category. This provides users with an additional resource for exploring DSA concepts interactively.
Changes Made:
Added Algomap.io link in the DSA Articles section.
Testing:
✅ Verified that the link is correctly added and working as expected.

docs: Add Algomap.io to DSA Articles

---

components/TopBar/CategoryDescriptions.ts
database/data.ts
database/index.ts
database/newsletters/devops.json

Fixes #2627
- Added a new subcategory "devopsLetters" under the "newsletters" category in the `devops.json` file.
- Included three DevOps-related newsletters: GitHub, Docker, and Kubernetes.
- Updated `file.ts` to include the new `devopsLetters` export.
- Updated `data.ts` to include the new `devopsLetters` subcategory under the "newsletters" category.

chore: added DevOps subcategory in the newsletter category

---

components/Cards/CardsList.tsx
pages/[category]/[...subcategory].tsx

Closes #2674 
This PR improves the cards sorting in subcategories by moving the sorting logic from CardsList to the subcategory level. This allows continuous alphabetical pagination across multiple subcategory pages.
These changes ensure consistent data presentation and improve user experience.

feat: Move alphabetical sorting to the subcategory level from the CardsList

---

database/data.ts

Closes #2713 
- Fixed a typo in the "Monitoring And Logging" subcategory name where "Logging" was misspelled as "Loggging".

fix: Correct typo in Monitoring And Logging subcategory (#2713)

---

database/frontend/ui_generators.json

Closes #2709
Change "UI Generators" subcategory in ui_generators.json to correctly refer ui_generators subcategory.
This PR not only fixes Shadcn UI (mentioned in the issue) but also:
- Patternizer
- Chakra UI
- CSS Portal
- Tailwind Components
- Meraki UI
- Tuk
- Tailwind Toolbox
- Tailwind UI

chore: fix ui_generators subcategory to show latest additions
